- lib/core/src/sdk.rs
- lib/core/src/swapper.rs
This fixes an issue that was introduces as part of extracting out the swapper trait.
The correct way to cooperate with the swapper for claiming our send swaps is:
1. First get a proof of payment by asking the claim_tx_details
2. Save the preimage and transition the swap state
3. Post the partial signed transaction to the swapper so they can claim.
Before this change we claimed in one step which could end up without us having the preimage and leaving the swap in status pending.
> Ensure we have preimage persisted before claiming

- lib/core/src/model.rs
- lib/core/src/persist/send.rs
- lib/core/src/sdk.rs
This PR fixes the handling of the `TransactionClaimed` Boltz event for send swaps.
We generally get the preimage in one of two ways:
- For cooperative claims, we get it as part of the interaction needed for the cooperative claim. Since this is the only time we get it, we immediately validate and persist it.
- For non-cooperative claims, we retrieve it from the onchain claim tx witness data. 
The handling of `TransactionClaimed` now distinguishes between the two cases and only attempts to retrieve the preimage from the onchain tx in case of non-cooperative claims (e.g. we don't already have it from a cooperative claim).
Depends on #268 
Closes #270
> Send: correctly handle `TransactionClaimed` Boltz event

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/lib.rs
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz_status_stream.rs
- lib/core/src/swapper/mod.rs
This PR moves the boltz status stream behind its own trait and as part of the swapper API.
Also took the opportunity to move persistent access out of the swapper trait by adding a ReconectHandler so the user of the trait has the opportunity (hook) to subscribe new list on every reconnection.
> Abstract swapper stream as part of swapper trait

- lib/core/Cargo.toml
The pinning of `security-framework` was causing a failure to build of windows. As the pinning is only needed for iOS builds, we only need to pin when the target_os is iOS.
```
error[E0433]: failed to resolve: could not find `unix` in `os`
--> C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\core-foundation-0.9.4\src\filedescriptor.rs:19:14
|
19 | use std::os::unix::io::{AsRawFd, RawFd};
|              ^^^^ could not find `unix` in `os`
|
note: found an item that was configured out
--> /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\os\mod.rs:26:9
note: found an item that was configured out
--> /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\os\mod.rs:64:9
error[E0432]: unresolved import `libc::PATH_MAX`
--> …
```
> Fix windows build

- lib/core/src/lib.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/wallet.rs
Here the send swaps state machine handling is extracted out to its own module with dependencies that can be mocked and allow us to write tests.
Also it removes the details from the sdk facade layer.
Once this is reviewed and merged, next in the line is the receive swaps handler.
> Send swap handler

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/lib.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
Extract out receive swap handling to its own module.
@dangeross also noticed you were right about the need to put the handlers as part of the LiquidSDK state as we subscribe to events on them therefore we should use a single instance for handling.
> Extract out receive swap handling logic

- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/mod.rs
ChainService is abstracted.
There are still specific instantiations of electrum inside Swapper & Wallet but this is due to the explicit dependency of these trait implementations in Electrum. This is OK IMO as these implementations are already behind traits.
> Abstract ChainService

- packages/dart/test/breez_liquid_dart_test.dart
- packages/flutter/example/lib/main.dart
- packages/flutter/example/lib/routes/connect/connect_page.dart
- packages/flutter/example/lib/routes/home/home_page.dart
- packages/flutter/example/lib/routes/home/widgets/bottom_app_bar.dart
- packages/flutter/example/lib/routes/home/widgets/payment_list/widgets/payment_item.dart
- packages/flutter/example/lib/services/breez_liquid_sdk.dart
- packages/flutter/example/pubspec.lock
- packages/flutter/example/pubspec.yaml
This PR addresses
- https://github.com/breez/breez-liquid-sdk/issues/260
- https://github.com/breez/breez-liquid-sdk/issues/264
`BreezLiquidSDK` wrapper class is introduced to handle stream subscription management similar to `BreezSDK`.
- Log stream should be subscribed early by on calling `BreezLiquidSDK.initializeLogStream()` on Dart entrypoint file of applications.
- Event stream subscription will be handle automatically on connecting to wallet.
Although most wallet API's are accessible through importing `'package:breez_liquid/breez_liquid.dart'`, they should be called via `BreezLiquidSDK.wallet` on application layer.
An internal helper method, `_fetchWalletData()`, is added to fetch wallet info and payment list when needed, _e.g.; after connecting to wallet & payments succeed etc._
- …
> [Flutter] Create reference implementation for Liquid SDK connection manager, event & log stream handler

- lib/core/src/swapper/boltz_status_stream.rs
This PR fixes a issue where swaps are not being subscribed to on (re)connect. 
In `on_stream_reconnect()` we are adding swaps to track via `track_swap_id()` which uses the `subscription_notifier` to add swap subscriptions. But because the `on_stream_reconnect()` is called before we subscribe to the `subscription_notifier` broadcasts, the initial subscriptions are lost as there is no receiver.
Fixes #173
> Fix (re)connect swap subscription

- .github/workflows/build-language-bindings.yml
- .github/workflows/publish-all-platforms.yml
- .github/workflows/publish-android.yml
- .github/workflows/publish-kotlin-multiplatform.yml
- .github/workflows/publish-python.yml
- .github/workflows/publish-swift.yml
- jitpack.yml
- lib/Cargo.lock
- lib/bindings/Cargo.toml
- lib/bindings/uniffi-bindgen.rs
- lib/core/Cargo.toml
- packages/react-native/example/android/app/build.gradle
- packages/react-native/example/android/build.gradle
This PR fixes:
- The working directories used during publishing
- Bumps uniffi_bindgen_kotlin_multiplatform to fix issues with generated callback interfaces (Logger, EventListener)
- Creating the Swift release
- The MVN url pre-check for jitpack
- Building the RN android example app
> Publish CI fixes

- lib/core/Cargo.toml
- lib/core/src/chain/liquid.rs
- lib/core/src/chain/mod.rs
- lib/core/src/chain_swap.rs
- lib/core/src/model.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils.rs
This PR reimplement the liquid chain service as a hybrid service. Still using electrum apart from the broadcast and get_script_history which uses the lowball node.
Also added verification for the swapper reported tx id and content before moving to the claim.
> Hybrid chain service

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
This PR forks the upstream lwk_wollet to add the same logic as in the bitcoin module. If no header is popped then try to subscribe to headers in case the connection was dropped. It might be that the client has reconnected and subscriptions don't persist across connections. Calling `client.block_headers_pop_raw()` doesn't reestablish a connection. Calling `client.ping()` won't help because the successful retry (when reestablishing a connection) will prevent us knowing about the reconnect and not able to re-subscribe to header notifications.
Fixes #314
> Workaround subscriptions not persisting with reconnects

- lib/core/src/chain_swap.rs
- lib/core/src/swapper/mod.rs
This PR refactors away the `refund_address` arg for `claim` calls, which was used to construct a temporary tx for retrieving partial musig signatures for the cooperative claim.
It encapsulates this logic in a new `get_claim_partial_sig` swapper method.
> Chaim swap claim: remove `refund_address` arg

- lib/core/src/chain/liquid.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
This fixes a regression introduced in HybridChainService PR where the non cooperative refund also used the lowball fee rate.
Also fixes the broadcast and script_history of chain service on testnet.
> Use lowball fees only on lockup and cooperative refund

- cli/src/commands.rs
- lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
- lib/bindings/src/breez_liquid_sdk.udl
- lib/bindings/src/lib.rs
- lib/core/src/bindings.rs
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.io.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
- packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKModule.kt
- packages/react-native/ios/BreezLiquidSDKMapper.swift
- packages/react-native/ios/RNBreezLiquidSDK.m
- packages/react-native/ios/RNBreezLiquidSDK.swift
- packages/react-native/src/index.ts
This PR adds monitoring of the lockup addresses of incoming chain swaps, to check the state of any unspent funds for the swap lockup address after the swap is finished. It will periodically:
- For every swap with a pending refund tx, check if the lockup address has any unspent outputs. If there are non, sets the swap to Failed/Complete.
- For every swap that is expired, check if the lockup address has any confirmed unspent outputs for a month (4320 blocks). If there are some, sets the swap to Refundable.
In addition the `prepare_refund` / `refund` interface is updated to allow multiple refunds of a swap (after swap the locktime).
The RefundPending state is added to help differentiate between a pending succeeding swap and a failed swap being refunded.
Fixes #324
> Monitor chain swap addresses

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/chain_swap.rs
- lib/core/src/receive_swap.rs
This PR:
- Moves the liquid transaction verification into the chain service and adds bitcoin transaction verification
- For chain swap statuses `transaction.server.mempool` & `transaction.server.confirmed`: 
- Verify the transaction exists in the script history
- Verify not RBF if only a mempool status
- Verify the amount is at least the minimum amount of the swap
Fixes #325
> Verify chain swap server lockup transaction

- lib/bindings/langs/flutter/justfile
This PR adds `just init-sdk` recipe to install Breez Liquid SDK requirements which will be used on CI runners.
> Added `just` recipe that installs SDK requirements

- cli/src/commands.rs
- cli/src/main.rs
- lib/core/src/lib.rs
This lets callers handle all imports with line
```rust
use breez_liquid_sdk::prelude::*;
```
> Add prelude

- lib/bindings/langs/flutter/justfile
- lib/bindings/langs/flutter/scripts/build-android.sh
- lib/bindings/langs/flutter/scripts/build_other.sh
This PR fixes the arguments used on non-grouped `just` recipes for building binaries for Apple, Android and other platforms.
- Ignore errors and create parent dir's as needed when using `mkdir` command
> Fix `just` recipe args for building binaries for Apple, Android and other platforms

- .github/workflows/build-bindings-flutter.yml
- .github/workflows/publish-all-platforms.yml
- .github/workflows/publish-dart.yml
- .github/workflows/publish-flutter.yml
- lib/bindings/langs/flutter/justfile
- lib/bindings/langs/flutter/pubspec.lock
- lib/bindings/langs/flutter/scripts/version.sh
- packages/dart/pubspec.yaml
- packages/flutter/README.md
- packages/flutter/android/CMakeLists.txt
- packages/flutter/example/pubspec.lock
- packages/flutter/example/pubspec.yaml
- packages/flutter/ios/flutter_breez_liquid.podspec
- packages/flutter/linux/CMakeLists.txt
- packages/flutter/macos/flutter_breez_liquid.podspec
- packages/flutter/pubspec.yaml
- packages/flutter/windows/CMakeLists.txt
This PR adds the necessary steps to the publishing CI to publish Dart and Flutter.
**Dart**
- Update Dart package files
- Tag the Dart package
**Flutter**
- Build android, ios & other artifacts
- Update Flutter package files
- Override pubspec with Dart tag
- Tag the Flutter package
- Release the package with artifacts
> Publish Dart and Flutter packages

- packages/dart/lib/breez_liquid.dart
`ExternalLibrary.process()` resolves any symbol in a library currently loaded with global visibility.
> Attempt to load Breez Liquid library via `ExternalLibrary.process()` if t fails to load via `open()`

- lib/core/src/persist/chain.rs
- lib/core/src/persist/send.rs
This PR includes `RefundPending` state in the list_pending filter. This is done for swaps that can be refunded, like Chain Swaps and Send Swaps.
Without this, refunded payments never transition away from `RefundPending` to `Failed` (refunded), because they're not considered a pending swap when handling the final transition.
> Fix transition from `RefundPending` to `Failed`

- packages/flutter/example/ios/Podfile.lock
- packages/flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/flutter/example/ios/Runner/AppDelegate.swift
- packages/flutter/example/ios/Runner/Info.plist
- packages/flutter/example/ios/Runner/Runner-Bridging-Header.h
- packages/flutter/example/lib/main.dart
- packages/flutter/example/lib/routes/home/widgets/balance.dart
- packages/flutter/example/lib/routes/home/widgets/payment_list/payment_list.dart
- packages/flutter/example/lib/routes/home/widgets/qr_scan/barcode_scanner_simple.dart
- packages/flutter/example/lib/routes/home/widgets/qr_scan/scanner_button_widgets.dart
- packages/flutter/example/lib/routes/home/widgets/receive_payment/receive_payment_dialog.dart
This PR adds various bug fixes & improvements on Flutter plugin example app.
- **Bugfix**: Wait `reconnect` attempt on startup
- Not waiting forced you to recover on each attempt even if your credentials were saved on device
- **Bugfix**: Bound the size of QR image view
- Reverse the payment list
- Should be reverted once this issue is addressed: 
#358 
- Do not show "No Balance" text when balance is 0
- Add required permissions for QR scan on iOS
- Add a cancel button to mobile scanner
- It was not possible to cancel scanning unless a valid QR was read on iOS
- Remove unneeded resource files from iOS Project
- Remove `breez_liquid_sdk.h`
- Remove outdated method to enforce bundling on AppDelegate
- Install pods
> Bug fixes & improvements on Flutter plugin example app

- lib/core/src/persist/mod.rs
If not excluded, they appear as separate Receive payments.
Fixes #365
> Update `list-payments`: exclude chain swap refunds

- packages/dart/pubspec.yaml
- packages/flutter/example/pubspec.yaml
This PR addresses CI failures on "Check Dart/Flutter bindings" step.
Reason for pinning to 2.0.0 instead of upgrading to 2.1.0:
* 2.1.0 has introduced a regression: https://github.com/fzyzcjy/flutter_rust_bridge/pull/2150#issuecomment-2213773291
- Respective issue: https://github.com/fzyzcjy/flutter_rust_bridge/issues/2194
> Pin `flutter_rust_bridge` to 2.0.0

- lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/utils.rs
- packages/dart/lib/src/frb_generated.io.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
This PR adds the method `estimate_refund_fees` so we can calculate the refund transaction without having to build it through lwk.
**Note:** There are some comments I left in regards to some unanswered questions, let me know what you think.
> Send: Fix refund `InsufficientFunds` error when calculating broadcast fee

- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
Remove `refund_send`, `refund_send_non_cooperative` from `sdk.rs`, which are also available in `swapper` module.
> Remove duplicate `refund_send`, `refund_send_non_cooperative`

- packages/dart/lib/src/bindings.freezed.dart
- packages/dart/lib/src/bindings/duplicates.freezed.dart
- packages/dart/lib/src/error.freezed.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/example/lib/main.dart
- packages/flutter/example/lib/routes/home/home_page.dart
- packages/flutter/example/lib/routes/home/widgets/drawer.dart
- packages/flutter/example/lib/routes/home/widgets/send_payment/send_payment_dialog.dart
- packages/flutter/example/lib/services/breez_liquid_sdk.dart
- packages/flutter/example/pubspec.lock
Closes #376
`wallet` on helper class, `BreezLiquidSDK` that manages wallet connection & SDK stream management is renamed to `instance`.
- Updates dependencies to latest
- Generate Dart bindings
> Rename `wallet` to `instance`

- .github/workflows/build-bindings-flutter.yml
- .github/workflows/publish-flutter.yml
Building of the "other" binaries has started to fail when publishing (and also locally after cleaning). I have removed the build-other phase as it was not used anyway.
This error in: https://github.com/breez/breez-sdk-liquid/actions/runs/9859878821/job/27224684219
```
error[E0308]: mismatched types
--> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-xwin-0.17.2/src/common.rs:642:40
|
642 |         Ok(builder.tls_config(Arc::new(client_config)).build())
|                               -------- ^^^^^^^^^^^^^ expected `ClientConfig`, found a different `ClientConfig`
|                               |
|                               arguments to this function are incorrect
|
= note: `ClientConfig` and `ClientConfig` have similar names, but are actually distinct types …
```
> Remove build-other from publish CI

- .github/workflows/publish-all-platforms.yml
This PR:
- removes the swift/kotlin requirement for flutter
- removes the waiting on swift for react-native (this fixes an issue building packages for the docs CI)
> Fix CI dependencies

- lib/bindings/src/breez_sdk_liquid.udl
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR changes the ordering of Payment fields to fix the python limitation of requiring non-default arguments before default arguments.
```
Traceback (most recent call last):
File "/home/runner/work/breez-sdk-liquid/breez-sdk-liquid/lib/bindings/tests/bindings/test_breez_sdk_liquid.py", line 1, in <module>
import breez_sdk_liquid
File "/home/runner/work/breez-sdk-liquid/breez-sdk-liquid/lib/target/tmp/breez-sdk-liquid-bindings-8c2ab1544e4e54dd/breez_sdk_liquid.py", line 2666
def __init__(self, tx_id: "typing.Optional[str]" = _DEFAULT, swap_id: "typing.Optional[str]" = _DEFAULT, timestamp: "int", amount_sat: "int", fees_sat: "int", preimage: "typing.Optional[str]" = _DEFAULT, bolt11: "typing.Optional[str]" = _DEFAULT, refund_tx_id: "typing.Optional[str]" = _DEFAULT, refund_tx_amount_sat: …
```
> Update UDL to fix python default argment ordering

- cli/src/commands.rs
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/bindings/src/lib.rs
- lib/core/src/bindings.rs
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.io.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/test_utils/chain.rs
- lib/core/src/test_utils/chain_swap.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/example/lib/utils/config.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidModule.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/ios/RNBreezSDKLiquid.m
- packages/react-native/ios/RNBreezSDKLiquid.swift
- packages/react-native/src/index.ts
This PR:
- adds an optional `sat_per_vbyte` param to `PreparePayOnchainRequest` to calculate the claim tx fees. 
- adds `recommended_fees()` method to find the optimal fee rate for the Bitcoin claim and refund.
Fixes #390
> Allow custom `pay_onchain` claim fees

- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.io.rs
- lib/core/src/frb_generated.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/flutter/example/pubspec.lock
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR changes the validation of the success action URL:
- Adds the `validate_success_url` param in the request to allow skipping domain validation
- Returns `matches_callback_domain` set to false on UrlSuccessActionData if there is a mismatch
> Update LNURL URL success action validation

- lib/bindings/src/breez_sdk_liquid.udl
Sets the default value so you don't need to define it in the language bindings
> Set `PreparePayOnchainRequest` `sat_per_vbyte` default value

- lib/core/src/sdk.rs
A `sync` call can take 2-3s.
IMO we don't need a `sync` when handling Boltz updates. For relevant new txs, we already add pseudo-txs.
> Remove `sync` call when handling Boltz update

- lib/core/src/persist/mod.rs
During Send Payment, the first state transitions caused the following:
- when the pending pseudo-tx was added, it had `timestamp = NOW`
- this causes `list_payments`, which sorts descending by `timestamp`, to show the new payment as the 1st
- the next `sync` will likely find the tx as unconfirmed
- this caused `insert_or_update_payment` to replace the pseudo-tx timestamp with `NULL`, as unconfirmed txs have no timestamp when coming from LWK
- this caused the Pending Send Payment to jump to the end of the `list_payments` response, as `NULL` values are considered lower than any set value and that query sorts descending
- one of the next `sync` calls would find the tx as confirmed
- this time, the tx comes with a timestamp from LWK
- `insert_or_update_payment` would change its timestamp in …
> Fix payment position fluctuation in `list_payments` for Send

- .github/workflows/main.yml
Going forward we need a more reliable way to maintain these brew dependencies, but for now this fixes the CI errors.
The error was caused by brew re-linking `rustup`, causing it and `cargo` to become unavailable
```
==> Migrating formula rustup-init to rustup
==> Unlinking rustup-init
==> Moving rustup-init versions to /opt/homebrew/Cellar/rustup
==> Relinking rustup
...
cargo run
make[2]: cargo: No such file or directory
```
> Fix React Native CI

- lib/core/src/sdk.rs
Previously we showed lowball fees when paying to an invoice with magic route hints, then proceeded to pay with regular fees (0.1 sats/vbyte). This PR fixes the issue so that the fees shown are the same as those used during the payment.
> Send: Show regular onchain fees when MRH payment is detected

- lib/bindings/README.md
- lib/bindings/langs/android/.gitignore
- lib/bindings/makefile
- packages/flutter/example/pubspec.lock
This PR is a pre-requisite for depending on `sdk-common` with `liquid` feature and addresses issues found within uniffi bindings.
- Correct the path of `breez_sdk_liquid.kt` on `.gitignore` 63ff806ab16e13f60e4661b1ab56fd5cffb6bcef
- Fix relative path on `bindings-android` script 0c9e08f3ead422036b8de66d848d60f7d95c0b49
- Update bindings `README.md` cca5efe70aaf204e93682ef177b0b60d58a9e7d2
- 'python' & 'swift' scripts are not available on this crate
- chore: ran melos pub-upgrade to address CI issues 0eac4f8161d850138fa6f02eeff27f00621d2da
> Bugfix: Correct the relative path on bindings scripts

- lib/core/src/chain/liquid.rs
- lib/core/src/receive_swap.rs
On Receive, we verify the lockup tx before marking the payment as `Pending`. This verification process involves fetching the script history for the lockup script, which may take a few seconds to detect the new lockup tx.
This PR reduces the backoff wait periods between retries (1s, 2s, 3s, etc) to a constant 1 second. The goal is that we detect the new tx and therefore emit the Payment Pending event as soon as possible.
Sample log output with the change:
```
[2024-08-01 16:12:53.113 INFO breez_sdk_liquid::receive_swap:67] Handling Receive Swap transition to "transaction.mempool" for swap DMLaBwrbz983
[2024-08-01 16:12:53.117 INFO boltz_client::swaps::liquid:367] Taproot creation and verification success!
[2024-08-01 16:12:53.119 INFO breez_sdk_liquid::chain::liquid:82] Fetching script …
```
> Receive payment: remove retry backoff, reduce wait time to 1 sec

- .github/workflows/publish-flutter.yml
- lib/bindings/langs/flutter/justfile
- packages/flutter/example/lib/routes/home/home_page.dart
- packages/flutter/example/pubspec.lock
- packages/flutter/example/pubspec.yaml
- packages/flutter/ios/flutter_breez_liquid.podspec
- packages/flutter/ios/flutter_breez_liquid.podspec.production
- packages/flutter/pubspec.yaml
This PR allows working with local library on iOS by using a different `podspec` for local & production environments.
- Create a `podspec` for local development 
- Use production `podspec` when publishing
---
These changes addresses CI warnings & a bug when running `just codegen` for the first time.
- ####  Flutter 3.24 changes
- Update SDK ranges
- Dart >= `3.5.0`
- Flutter >= `3.24.0`
- Update dependencies to latest using `melos pub-upgrade`
- ####  Bugfix:
- Correct the output folder creation on `codegen` just recipe
- This would have caused an error on devices that would run `just codegen` for the first time, as the output folder wouldn't have existed
> Allow working with local library on iOS

- lib/core/src/bindings.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
Fix indentations on documentations.
> Address `cargo clippy` warnings

- lib/core/src/sdk.rs
- packages/flutter/example/pubspec.lock
This PR removes the amount validation of the BIP21 in the magic routing hint.
> Receive payment: remove MRH BIP21 amount validation

- lib/core/src/chain_swap.rs
- lib/core/src/persist/chain.rs
- lib/core/src/sdk.rs
This PR changes the chain swap so that once the claim tx is broadcast it keeps the state pending (waiting confirmation event is emitted) and waits for confirmation before setting it to complete. For the incoming chain swap the `sync()` monitors the claim tx, for outgoing chain swap the claim address is checked periodically to see if the tx is confirmed.
See: https://github.com/breez/breez-sdk-liquid/pull/399#discussion_r1716713556
> Confirm chain swap claims

- .github/workflows/main.yml
- .github/workflows/publish-flutter.yml
- lib/bindings/langs/flutter/justfile
- lib/bindings/langs/flutter/pubspec.lock
- lib/bindings/langs/flutter/pubspec.yaml
- lib/bindings/langs/flutter/scripts/version.sh
- packages/flutter/ios/flutter_breez_liquid.podspec
- packages/flutter/ios/flutter_breez_liquid.podspec.production
Closes #417
This PR addresses a regression caused with changes on 
- #434
and makes several improvements to version script. Making it easier to use with the addition of `just version` recipe & correctly sets `ROOT` relative to the script's location.
- fix: Update production podpsec's version with version script
- Resolve relative path of root from script directory
- Ran 'just version'
- Ran `melos pub-upgrade`
- Updated melos dependency
- Update versions on podspec & cmake scripts when publishing Flutter plugin
- Check if versions on podspec & cmake scripts were updated using version script on CI
> Bugfix: Update production podpsec's version with version script

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/bindings/src/lib.rs
- lib/core/Cargo.toml
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/bindings.freezed.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/makefile
- packages/react-native/src/index.ts
- Depend on `sdk-common` with `liquid` feature
- chore: ran `cargo update`
- Add `copy` script to `packages/react-native` `makefile`
- `copy` script is useful if uniffi bindings are recently generated, it saves time by not regenerating android, ios and rn bindings
- Reordered scripts
> Depend on `sdk-common` with `liquid` feature

- lib/core/src/sdk.rs
This PR addresses an ambiguity in `validate_chain_pairs` :
```
// before
fn validate_chain_pairs(&self, direction: Direction, amount_sat: u64) -> Result<ChainPair, PaymentError>
// after
fn validate_chain_pairs(&self, direction: Direction, payer_amount_sat: u64) -> Result<ChainPair, PaymentError>
^^^^^^^^^^^^^^^^
```
This originally caused the method to be used both with `receiver_amount_sat` and with `payer_amount_sat` as args, whereas for both chain swap types, the `payer_amount_sat` is correct.
In addition, this PR adds a few comments and renames a few variables in related amount validation methods.
> Fix chain swap limits validation

- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/error.rs
- lib/core/src/frb_generated.io.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/error.dart
- packages/dart/lib/src/error.freezed.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR adds support for using a description hash in the create reverse swap request. This can then be used in the LNURL-pay flow to hash the metadata. 
Even though there is broad adoption to drop the validation of the metadata description hash, it is as yet not merged: https://github.com/lnurl/luds/pull/234
> Add description hash to receive payment

- lib/core/src/sdk.rs
This emits the PaymentPendingConfirmation event for direct liquid payments.
fixes #458
> Emit pending confirmation for liquid transactions

- lib/bindings/uniffi.toml
This PR fixes the visibility of exported symbols by overriding the access modifier in the [uniffi config](https://github.com/NordSecurity/uniffi-bindgen-cs/blob/eae12c25a315d52a4ea9b2d7c49f723b9900750c/docs/CONFIGURATION.md?plain=1#L57).
> Fix C# symbol export

- lib/bindings/src/breez_sdk_liquid.udl
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR sets the optional params in the UDL as default `null` so that they are not required to be past into the binding classes (e.g. python, kotlin, swift)
> Set optional prepare params as null

- lib/bindings/langs/react-native/src/gen_kotlin/templates/EnumTemplate.kt
- lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt
- lib/bindings/langs/react-native/src/gen_kotlin/templates/RecordTemplate.kt
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/example/App.js
- packages/react-native/example/ios/Podfile.lock
- packages/react-native/example/yarn.lock
This PR adds a function to replace ReadableArray.toArrayList() to prevent any nested objects being converted to HashMap instead of kept as ReadableMap.
Fixes #479
> RN: Prevent conversion of ReadableMap to HashMap

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR changes the `short_channel_id` of the `RouteHintHop` model to string in the format:
```
<BLOCK_HEIGHT>x<TX_INDEX>x<OUTPUT_INDEX>
```
Depends on https://github.com/breez/breez-sdk-greenlight/pull/1082 (CI errors until merged)
Fixes #480
> Change short_channel_id to string

- .github/workflows/build-bindings-flutter.yml
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPayInvoice.kt
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/LnurlPayInvoice.swift
This PR fixes:
- `No space left on device` error when running build-bindings-flutter
- The change of argument ordering calling `PrepareReceiveRequest`
https://github.com/breez/breez-sdk-liquid/actions/runs/10811346459
> Fix publish CI issues

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/sdk.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/swapper.rs
This PR bumps the `boltz-rust` library and adjusts the calls to some of the changed method signatures.
> Bump boltz client library

- lib/bindings/langs/android/lib/proguard-rules.pro
- lib/bindings/langs/android/lib/src/main/AndroidManifest.xml
- lib/bindings/langs/kotlin-multiplatform/breez-sdk-liquid-kmp/build.gradle.kts
- lib/bindings/langs/kotlin-multiplatform/breez-sdk-liquid-kmp/consumer-rules.pro
> Duplicate class technology.breez.BuildConfig found in modules breez-sdk-0.5.2.aar -> jetified-breez-sdk-0.5.2-runtime (com.github.breez:breez-sdk:0.5.2) and breez-sdk-liquid-0.3.1-dev3.aar -> jetified-breez-sdk-liquid-0.3.1-dev3-runtime (com.github.breez:breez-sdk-liquid:0.3.1-dev3)
This PR fixes the namespace conflict between the Greenlight and Liquid SDK for Android and Kotlin Multi-Platform (and React Native).
Tested the build using:
```
"@breeztech/react-native-breez-sdk": "^0.5.2",
"@breeztech/react-native-breez-sdk-liquid": "0.3.1-dev4",
```
> Fix the namespace conflict

- .github/workflows/publish-flutter.yml
This PR removes the gitignore for ios/macos to allow Sources to be published to the package.
See https://github.com/breez/breez-sdk-liquid-flutter/pull/2
> Fix publishing of Flutter sources

- .github/workflows/main.yml
- lib/bindings/langs/flutter/justfile
- lib/bindings/langs/flutter/scripts/build_ios_framework.sh
- lib/bindings/langs/flutter/scripts/build_uniffi_android.sh
- lib/bindings/langs/flutter/scripts/build_uniffi_swift.sh
- lib/bindings/makefile
Re-add the convenience Flutter `gen` command to generate code/FFI bindings and softlink C headers
> Re-add convenience Flutter gen command

- lib/core/src/chain_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
This fixes the "Liquid chain used for Bitcoin operations" error, which came up when a refund was initiated.
> Chain swap cooperative refund: fix triggering of `refund_incoming_swap`

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/swapper/boltz/mod.rs
Closes #521.
The new Bitcoin chain service method `fetch_script_utxos` introduced a regression where the output would reference a p2sh script rather than the appropriate script pubkey.
Additionally, this PR also changes part of the refund transaction creation logic to include the swap's preimage in the size calculation, both for completeness' sake (to avoid possible off-by-1 errors, as preimages can be 32 or 33 byte) and to reduce the amount of arguments pass to the inner methods.
> Fix: Incoming Chain Swap Refund

- lib/core/src/model.rs
This PR brings in our own Electrum server for Liquid Mainnet.
> Add Breez electrum server for Liquid Mainnet

- .github/workflows/main.yml
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
This PR adds CI job to check the notification plugin builds and fixes the error in the SwapUpdated job
CI run catching failure: https://github.com/breez/breez-sdk-liquid/actions/runs/11322349480/job/31482892625
> Add notification plugin CI

- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/flutter/breez_sdk_liquidFFI/include/breez_sdk_liquidFFI.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/bindings/src/lib.rs
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/bindings.freezed.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidModule.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/ios/RNBreezSDKLiquid.m
- packages/react-native/ios/RNBreezSDKLiquid.swift
- packages/react-native/src/index.ts
This PR adds a `prepare_lnurl_pay()` interface method as a step before `lnurl_pay()` to calculate the fees involved with the payment, whether it is a payment via Lightning or paid directly to a Liquid address using the Magic Route Hint retrieved in the invoice.
Depends on https://github.com/breez/breez-sdk-greenlight/pull/1104 (CI tests will be broken)
Fixes #468
> Add prepare_lnurl_pay

- .github/workflows/publish-swift.yml
This PR fixes the publish CI `publish-swift` to checkout the correct SDK branch
> Fix SDK checkout

- lib/core/src/chain_swap.rs
- lib/core/src/send_swap.rs
This PR ensures we log the root cause when we get "could not retrieve address from swap script" errors.
> Log exact error root cause when failing to lookup script address

- lib/core/src/chain_swap.rs
This PR changes the missed tick behaviour for scanning chain swaps to Skip. There is no advantage to using Burst as our scanning depends on the current block height.
> Skip missed ticks

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/buy.rs
- lib/core/src/chain_swap.rs
- lib/core/src/persist/receive.rs
- lib/core/src/sdk.rs
- lib/core/src/test_utils/persist.rs
This PR fixes older TODOs about amount type conversions: some amounts and fees are `u64`, while others were `u32`.
Fixing this also simplifies the code for amountless swaps, which deals with `Option<u64>`.
> Bring remaining u32 amount types to u64

- lib/core/src/chain_swap.rs
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/receive.rs
- lib/core/src/receive_swap.rs
This PR prevents a double claim by:
- Checking the swap's `claim_tx_id` immediately before creating a claim tx
- Storing the txid for the created claim tx before broadcasting using a function that prevents overwriting the `claim_tx_id`
- Broadcasts the claim tx only if the storing of the txid is successful
- Unset the `claim_tx_id` if chain service/swapper broadcasts both fail
> Prevent swap double claim

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/src/lib.rs
- lib/core/Cargo.toml
- lib/core/src/chain_swap.rs
- lib/core/src/error.rs
- lib/core/src/model.rs
- lib/core/src/persist/address.rs
- lib/core/src/persist/cache.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/wallet.rs
This PR:
- Adds addresses allocated to swaps to a reserved pool of addresses until the swap expires
- Gets the next unused address from either an expired reserved address or the next index from the cached derivation index
- Caches the last used derivation index
- Associates a magic routing hint address to the reverse swap, which then when paid via this address, is linked to the reverse swap (if the address is unused, it will be reallocated after expiry)
TODO:
QUESTIONS:
- Should a payment created using a LiquidAddress method expire?
Fixes #523
> Reserved address pool

- lib/core/src/persist/send.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
Given the current event loop, TimedOut payments may cause lockups to be broadcast. 
This PR changes the send flow such that:
1. When a user calls `send_payment`, the lockup is broadcasted within that same thread _only if_ it hasn't been broadcasted beforehand
2. The background thread (Boltz status stream) does not execute lockups any longer
~**TODO:** Persist `lockup_tx_id` beforehand to ensure we don't broadcast twice in case the client closes the application before the new state is saved~
> Send: Fix double-lockup when payment is TimedOut

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/lnurl/auth.rs
This PR bumps `sdk-common` to the latest version and propagates the changes introduced in https://github.com/breez/breez-sdk-greenlight/commit/a247b9508695a41a513d7fd1ff71a2d84844b73c , namely making the methods `async`.
> Propagate signer interface changes

- lib/core/src/sdk.rs
This PR adds more logging to the start of the onchain payment flow, so that we can better determine which path was taken when troubleshooting: that of drain, or pay user-specified amount.
> Onchain payment flow: add more logging

- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
This PR:
- Fixes chronological payment ordering, first ordering by swap creation timestamp then tx timestamp
- Fixes use of tx timestamp in payment 
Fixes #540
> Fix chronological order of `list_payments`

- lib/core/src/chain_swap.rs
- lib/core/src/sdk.rs
This PR retries adds monitoring of the incoming server lockup txs. If a server lockup tx is confirmed without a claim (tx failed verification when receiving the Boltz status), then perform the claim.
Fixes #547
> Retry chain swap server lockup tx verification

- packages/react-native/android/build.gradle
This handles relative paths better. For instance, we use a Monorepo where our `node_modules` is located somewhere else.
> Android: Replaced  with "$rootDir" with "$projectDir"

- lib/bindings/langs/swift/Sources/BreezSDKLiquid/SDKNotificationService.swift
Fixes an issue from PR #567 where there is a compatibility issue initialising the workingDir URL in the Swift Notification Plugin.
> Fix Swift URL init compatibility

- lib/core/src/persist/mod.rs
This PR fixes the receive payment Lightning details to include the preimage.
Fixes #570
> Add preimage to receive payment

- lib/core/src/error.rs
- lib/core/src/sdk.rs
The Moonpay API defines BTC amounts as having `precision = 5`, so only 5 decimals are considered. This means sat amounts must be mutiples of `1_000`.
When this is not the case, the Moonpay URL shows an ambiguous error:
> "Invalid queries, check 'errors' property for more info."
which, when checked, shows another ambiguous
> quoteCurrencyAmount must be a decimal number
thrown by the [getbuyquote](https://dev.moonpay.com/reference/getbuyquote) endpoint. Here, `quoteCurrencyAmount` is the sat amount expressed as BTC (e.g. `0.0005`).
> Add precision validation for Moonpay call

- lib/core/src/persist/mod.rs
Send / Receive LN Swaps should fallback to "Lightning transfer".
> Fix typo in fallback payment description

- lib/bindings/langs/swift/Sources/BreezSDKLiquid/SDKNotificationService.swift
This might a bit too Expo specific but the approach isn't bad IMO. Expo offers a API for sending push notifications to Android and iOS without having to worry about APN certificates or Firebase credentials. Because of that, Expo standardizes the payload a little and shoves anything custom to a property called `body` to avoid interference with Expo own properties.
> Payload compatibility for Expo Notifications

- lib/core/src/persist/mod.rs
This PR updates the list payments details query by Bitcoin address to check the lockup address for incoming and claim address for outgoing chain swaps.
> Use lockup or claim address for Bitcoin address query

- .github/workflows/build-bindings-ios.yml
This PR adds the IPHONEOS_DEPLOYMENT_TARGET env in the CI to prevent the following error in the `aarch64-apple-ios` build:
```
ld: warning: object file (/Users/runner/work/breez-sdk-liquid/breez-sdk-liquid/lib/target/aarch64-apple-ios/release/deps/liboslog-2986680f3acc6ccb.rlib[4](db3b6bfb95261072-wrapper.o)) was built for newer 'iOS' version (18.1) than being linked (10.0)
ld: warning: object file (/Users/runner/work/breez-sdk-liquid/breez-sdk-liquid/lib/target/aarch64-apple-ios/release/deps/libdart_sys_fork-f573a0ab53d8c10b.rlib[4](248f927bf32daba4-dart_api_dl.o)) was built for newer 'iOS' version (18.1) than being linked (10.0)
Undefined symbols for architecture arm64:
"___chkstk_darwin", referenced from:
_BN_mod_exp_mont_consttime in …
```
> Set IPHONEOS_DEPLOYMENT_TARGET in CI

- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/model.rs
- lib/core/src/persist/sync.rs
- lib/core/src/signer.rs
- lib/core/src/sync/client.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/client.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/sync/model/mod.rs
- lib/core/src/test_utils/mod.rs
- lib/core/src/test_utils/sync.rs
- lib/core/src/test_utils/wallet.rs
Closes #502, closes #503.
Based on #555.
> Real-time Sync: Add pull and merge

- lib/Cargo.lock
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/persist/sync.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/client.rs
- lib/core/src/sync/model/sync.rs
- lib/core/src/test_utils/sync.rs
Based on #555 and #556.   
Closes #504, closes #505.
**TODO:**
> Real-time Sync: Add push logic and run method

- lib/core/src/persist/cache.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/sync.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/sync/model/mod.rs
Based on #555, #556, #568, #578.
> Real-time Sync: Track latest address derivation index

- cli/src/main.rs
- lib/Cargo.toml
- lib/bindings/Cargo.toml
- lib/bindings/langs/react-native/Cargo.toml
- lib/core/Cargo.toml
This PR adds a workspace-wide `clippy` lint config.
This allows us to selectively allow `empty_line_after_doc_comments`, which is caused by the the combination of a recent bump in rust version (which now classifies this as a warning) and a uniffi rust file generated  by `uniffi_macros` (which causes this to trigger because of an extra space after some rustdocs).
> Fix clippy CI step

- cli/src/commands.rs
A field rename was not propagated to the CLI.
This PR fixes that.
> Fix CLI reference

- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/bindings/src/lib.rs
- lib/core/Cargo.toml
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/test_utils/swapper.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/lib.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidModule.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/ios/RNBreezSDKLiquid.m
- packages/react-native/ios/RNBreezSDKLiquid.swift
- packages/react-native/src/index.ts
> External input parsing

- lib/core/src/persist/chain.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
**Note:** Instead of `ON CONFLICT DO UPDATE SET` I've opted for `ON CONFLICT DO NOTHING` followed by a secondary statement where we selectively update the fields of interest (just like it was previously)
> Real-time Sync: fix swap update flow

- cli/Cargo.lock
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/chain_swap.rs
- lib/core/src/test_utils/chain.rs
This PR improves the robustness of handling the quote validation by retrying to get the script balance in case the electrum server has not seen the tx yet.
- Adds retries to getting the user lockup script balance when validating the zero-amount chain swap server lockup quote
- Uses non-blocking sleep when retying
Fixes #601
> Zero-amount quote get balance retry

- lib/core/src/persist/chain.rs
- lib/core/src/sync/model/data.rs
This PR pushes the `payer_amount_sat` & `receiver_amount_sat` to the rt-sync for updating non-local instances.
> Real-time Sync: update payer/receiver amounts

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/flutter/breez_sdk_liquidFFI/include/breez_sdk_liquidFFI.h
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
This adds ExternalInputParser struct to the flutter rust bridge mirrors to pull it in from the sdk-common crate
> Add ExternalInputParser mirror for frb

- lib/core/src/persist/chain.rs
This PR fixes the storage of the chain swap claim_address adding it into the SQL UPDATE statement.
> Fix recover claim address storage

- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/wallet.rs
This PR:
- Filters the incoming txs for an MRH script by swap `created_at` timestamp, so an MRH tx will only be associated with a swap when: 
- swap has no claim/lockup txs
- MRH tx height less than swap timeout block height
- MRH tx block timestamp greater than swap created timestamp
- Adds a 5 index buffer to the wallet full scan incase our cached derivation index is behind
Fixes #607
> Increase MRH robustness

- lib/core/src/persist/mod.rs
Before this PR pending liquid transactions that were synced were shown at the bottom of the list payments.
This is because their timestamp was null as there was no swap and the transactions was in the mempool.
Now it fallbacks to the current timestamp for pending transaction.
fixed https://github.com/breez/breez-sdk-liquid/issues/611
> fix liquid panding timestamp

- lib/core/src/lib.rs
- lib/core/src/model.rs
- packages/dart/lib/src/model.dart
Some minor doc fixes.
Makes the `receive_swap` module public so that the constants can be accessed.
> Minor docs fixes

- lib/core/src/sync/client.rs
Before this PR after some time the sync requests started to receive transport errors. It seems that the default keep alive settings are not working well for this service and we have to configure the underline grpc channel properly.
Also the way we inject the API key has changed a bit to a more centralised point to keep the API calls cleaner.
> Use configured lazy connect channel in sync service

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/model.rs
- lib/core/src/persist/sync.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/sync/model/mod.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR:
Needs PR https://github.com/breez/breez-sdk-greenlight/pull/1148
Fixes #318
> Store & Sync LNURL info

- lib/core/src/chain_swap.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/core/src/receive_swap.rs
- lib/core/src/send_swap.rs
This PR allows a payment event to be emitted without a tx_id and updates the payments query to:
- do a FULL JOIN with the chain_swaps table (include chain swaps without claim txs) filtering out where the swap state is Created or TimedOut
- filter out receive_swaps where the swap state is Created, Failed or TimedOut
Fixes https://github.com/breez/misty-breez/issues/276
```
{
"destination": null,
"tx_id": null,
"timestamp": 1734626434,
"amount_sat": 47796,
"fees_sat": 2204,
"swapper_fees_sat": 50,
"payment_type": "Receive",
"status": "Pending",
"details": {
"Bitcoin": {
"swap_id": "tYJ9vuAa828n",
"description": "Bitcoin transfer",
"refund_tx_id": null,
"refund_tx_amount_sat": null
}
}
}
```
> Update list payments to include chain swaps with only user lockup

- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
A temporary fix for #628. 
The next step would then be to group balance by asset ids
> Consider only L-BTC when calculating wallet balance

- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/Constants.kt
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/SwapUpdated.kt
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Constants.swift
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
If a payment is waiting fee acceptance, let's show a notification asking the user to review the payment.
> Show notification if payment requires fee acceptance

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils/persist.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR stores the unblinding data which can be used in the `blinded` param when unblinding the transaction in any Liquid explorer. See: https://docs.liquid.net/docs/unblinding-transactions
> Store unblinding data for the tx

- lib/core/src/persist/chain.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/sync/model/data.rs
This PR pre-checks the updated swap against the existing swap, if some fields are updated then commit outgoing sync
(Draft while I can't test with rt-sync)
> Pre-check updated fields before committing outgoing sync

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/sdk.rs
- lib/core/src/utils.rs
This moves bolt12 parsing into sdk-common. Check accompanying PR: https://github.com/breez/breez-sdk-greenlight/pull/1152.
> Move bolt12 parsing to sdk-common

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/core/src/bindings.rs
- lib/core/src/frb_generated.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
This should have been done in #615. Created #643 so that such mistakes can be easily avoided.
> Fix missing dart bindings

- lib/core/src/recover/recoverer.rs
We should only set the actual payer amount if there is some user lockup amount. Without this fix, incoming chain swaps show the amount zero until the recovery process runs.
> Fix actual payer amount recovery

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/sdk.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/sync/model/mod.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/test_utils/sync.rs
- lib/core/src/utils.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR:
- adds the invoice's destination pubkey (bolt11: payee pubkey, bolt12: signing pubkey) to the payment details as `destination_pubkey`
- renames the payment detail's `bolt11` to `invoice` to expose both bolt11 and bolt12 invoices
Depends on https://github.com/breez/breez-sdk-greenlight/pull/1156
Fixes #646
Fixes #648
> Add destination pubkey and bolt12 invoice to payment details

- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/sdk.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/persist.rs
Addresses one of the causes of #647 
The idea is to add an incrementing version to the local swap data to check that it didn't change when performing read -> update -> write operations. An incrementing version was preferred instead of a timestamp to avoid potential issues with clock precision, which could cause a write to not be detected.
Triggers are used to make sure any update increases the version. Updates based on a previously read swap only go through if the version didn't change in the meantime.
> Implement optimistic locking for read-update-write swap operations

- lib/core/src/persist/migrations.rs
The changes from #652 were cherry-picked onto the `v0.6.0` release branch, which doesn't and won't include the changes from #649. This PR sets the migrations ordering accordingly.
> Fix migrations ordering

- lib/core/src/recover/recoverer.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/utils.rs
Addresses one of the causes of #647.
Because of some concurrency issues, a send swap refund tx could be misclassified as a claim tx due to it not being seen as an incoming tx. This PR does not attempt to address the causes for that misclassification, which were addressed in #652, but instead:
- Verifies recovered preimages if found
- If the preimage is not already known or couldn't be recovered and validated, the potential claim tx is ignored
> Ignore claim tx if preimage is not known or invalid

- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
- lib/core/src/utils.rs
#630 introduced a regression on testnet, as the asset ID between testnet and mainnet L-BTC is different. 
This PR fixes this temporarily. should become unnecessary once #645 is merged.
> Fix: Add L-BTC asset matching network type

- .github/workflows/main.yml
- cli/Cargo.lock
- lib/core/src/chain_swap.rs
- lib/core/src/persist/chain.rs
This fixes an issue where multiple instances compete for broadcasting the claim tx of a chain swap. We defined that only the instance that created a swap should be able to broadcast a TX associated with that swap.
> Fix: prevent non-local chain swap claim

- lib/core/src/sdk.rs
While the pending balance calculation uses the local database, the confirmed balance uses LWK. We need to filter LWK's transactions based on whether or not they're confirmed.
> Consider only confirmed transactions for wallet balance

- lib/core/src/persist/receive.rs
When the swap is paid via MRH, the recoverer sets the `payer_amount_sat` / `receiver_amount_sat` to the MRH tx amount so the payment shows no fees. This fix updates these amounts in the db .
Fixes #666
> Store the payer/receiver amount for MRH

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/model.rs
We compare swap instances at least in the methods `update_swap()` and `update_swap_info()` in order to know if an update needs to be or was made. Given the introduction of the `version` field in #652, these comparisons may not work as expected because, in an update where all updated fields don't produce changes, the version will still be incremented. In this case, an update would triggered/detected even when that shouldn't be the case.
This PR makes use of the crate `derivative` to implement `PartialEq` while ignoring the `version` field.
> Fix swap structs PartialEq implementation

- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
This PR:
- Fixes receiver amount calculation - before, an over/underpaid swap could be shown as having 0 fees.
- Fixes `is_waiting_fee_acceptance()` - before, an over/underpaid swap could get to the state of WaitingFeeAcceptance
> Fix amountless receiver amount and waiting fee acceptance condition

- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/sync/mod.rs
- lib/core/src/test_utils/recover.rs
- lib/core/src/test_utils/sdk.rs
- lib/core/src/test_utils/swapper.rs
This PR adds the recovery of a submarine swap's preimage from the swapper/blockchain, with the following fallbacks:
- Swap has preimage: Don't recover
- Swap has no preimage: Recover cooperatively (single request)
- Swap has no preimage and cannot recover cooperatively: Recover non-cooperatively (batch request)
**Note:** Had to switch to a local fork as there is a pending PR to include these changes on Boltz's side
**Note:** It would be nice to have batch requests also for the Boltz API to reduce overhead, maybe something for them to consider adding
> Recoverer: Add cooperative preimage recovery and optimize flow

- cli/Cargo.lock
- lib/core/src/model.rs
Getting an overflow calculating the payment fees_sat. It's from a incoming chain swap that was underpaid. I have used `saturating_sub` to prevent the overflow.
```
thread 'tokio-runtime-worker' panicked at /Users/rosssavage/Source/Projects/breez-sdk-liquid/lib/core/src/model.rs:1560:23:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is the PaymentSwapData causing the issue:
```
[2025-01-17 14:56:33.613 DEBUG breez_sdk_liquid::model:1548] Swap ID pending: PaymentSwapData { swap_id: "83CFncYW8e8R", swap_type: Chain, created_at: 1733902652, expiration_blockheight: 874405, preimage: Some("408dd22e5bf613b4d055c22ad2a1a79ba112e03b95237a3dacd305388fcd83f1"), invoice: None, bolt12_offer: None, payment_hash: None, …
```
> Ensure fees are calculated without overflow

- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
This fixes the derivation of an incoming chain swap state from onchain data. Specifically, the `is_refundable` condition, which should detect any over/underpayment as a refundable, but was only covering underpayments.
> Fix receive chain swap `is_refundable` condition

- cli/src/commands.rs
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR adds the ability to sort payments by ascending/descending timestamp (defaulting to descending, as it was up until now).
> Add `sort_ascending` flag to list_payments

- cli/src/main.rs
- lib/bindings/src/breez_sdk_liquid.udl
- lib/bindings/tests/bindings/csharp/Program.cs
- lib/bindings/tests/bindings/golang/test_breez_sdk_liquid.go
- lib/bindings/tests/bindings/test_breez_liquid_sdk.cs
- lib/bindings/tests/bindings/test_breez_sdk_liquid.kts
- lib/bindings/tests/bindings/test_breez_sdk_liquid.py
- lib/bindings/tests/bindings/test_breez_sdk_liquid.swift
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/cache.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/persist/sync.rs
- lib/core/src/sdk.rs
- lib/core/src/sync/client.rs
- lib/core/src/sync/mod.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/test_utils/sdk.rs
- lib/core/src/test_utils/sync.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Closes #661.
Built on top of #637.
This PR:
- Makes the real-time sync service optional (depending on the presence of `sync_service_url`) as follows:
- Set and equal to `BREEZ_SYNC_SERVICE_URL`: Check for API key
- Set and different from `BREEZ_SYNC_SERVICE_URL`: Use without API key
- Not set: Disable the sync service
- Conditionally calls rt-sync commit methods to avoid cluttering of the db when the sync service is not active
- Skips the initial `validate_api_key` call unless it is set in the config
This should complete all the requirements for #554, except for the swapper proxy changes & fiat api.
> Remove mandatory API key checks

- lib/core/src/persist/mod.rs
Includes the liquid payments in the list payments query by state when updating the pending balances
> Include non-swap state in list payments query

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This adds a new PaymentRefundable event for when a swap gets into the state Refundable. Integrators can use it to trigger a refresh of the refundable swap list.
> Add SdkEvent for refundable swap

- lib/Cargo.lock
- lib/core/Cargo.toml
This prevents issues with using the SDK as a rust dependency. When added to a new project, the dependencies are not locked, causing issues if boltz client suffers some non-backward compatible change to the interface.
CI was currently failing for this exact reason. #682 also fixes the CI failure by upgrading the SDK, but we should specify the rev regardless.
> Set specific rev for Boltz client crate

- cli/Cargo.lock
- lib/core/src/sdk.rs
This adds validation of the refund_address input for the refund methods. Besides leading to more comprehensible errors in case of an invalid input, it also allows the use of the BIP21 format as input.
> Validate refund address input

- cli/Cargo.lock
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #539
This PR:
- Reimplements UTXO listing in order for only confirmed txs to be considered (both in the SDK, as well as in boltz-client - [upstream PR](https://github.com/SatoshiPortal/boltz-rust/pull/87))
- Sets RefundPending as a refundable state
- Adds the refund tx id to the items returned by `list_refundables` so that pending refunds can be easily distinguished from refunds
~~Note: still have to test if this works for non-coop refunds. Need to wait for the timelock to expire.~~ Works well for non-coop refunds as well
Test notes:
- After a refund has been started for a certain swap, it should still be shown as available for refund. New refunds can be prepared and broadcast.
> Chain swap refund tx fee bumping

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/sync/model/mod.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/sync.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #631.
This PR adds a boolean field to BTC address payments that indicates if an amountless swap had its fees auto-accepted. This is added to the synced fields so that other instances of the SDK can learn about it.
> Expose amountless swap fees auto acceptance

- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPayInvoice.kt
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/LnurlPayInvoice.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/chain_swap.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/test_utils/wallet.rs
- lib/core/src/wallet.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/example/App.js
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR:
**Testing Notes:**
- It's important that the addition of assets handling does not impact swaps
- No other additional testing as Misty doesn't support assets, although there are addition testing notes in https://github.com/breez/misty-breez/pull/323
> Multi-asset send/receive

- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/bindings.rs
- lib/core/src/error.rs
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/asset_metadata.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/bindings.dart
- packages/dart/lib/src/error.dart
- packages/dart/lib/src/error.freezed.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Builds on PR #645 
This PR:
Depends on https://github.com/breez/breez-sdk-greenlight/pull/1157
> Configure asset metadata

- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
This PR adds a PairLimits check in the `is_refundable` condition when deriving the current state of a chain swap. Without it, an amountless swap for which the user locks up too little/too much funds will not be correctly derived as refundable.
Test notes:
- Create an amountless receive to BTC address and send an amount below the indicated minimum. After the Bitcoin tx confirms, the payment should be shown as refundable.
> Consider PairLimits in is_refundable condition

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/send_swap.rs
- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/liquid.rs
Reflect changes from SatoshiPortal/boltz-client@db045fbd94f4708aa962e572473221a717954e59
> Explicitly set absolute fees when signing transactions

- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
- lib/core/src/wallet.rs
This PR does 2 things:
1. Use a single point to scan the lwk_wallet (from the background task)
2. Use a cached electrum client (and connection) to scan the wallet. It saves the connection creation on each scan.
The ElectrumClient wraps a Client (from electrum-client) crate which holds the tcp connection.
I think we should aim for holding one client with reasonable timeout and on top of it we can instantiate several ElectrumClient when we need. The goal of the high level ElectrumClient is only to implement the API in a more convenient way (just a wrapper) by implementing BlockchainBackend for lwk_wallet. Currently the API doesn't allow it and I will work on that in a following PR.
Testing Notes: Test sync with two devices for send/receive
> Use cached electrum client connection for full_scan

- cli/src/commands.rs
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/test_utils/swapper.rs
- lib/core/src/utils.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Closes #559 
- Drain the balance to a LNURL-pay or lightning address
> LNURL-pay drain

- lib/core/src/persist/chain.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
This PR changes the chain swap update query to allow overwrites of the refund tx id, which can now change due to potential fee bumps using RBF. 
Additionally, it simplifies the code using coalesce in the same query and the analogous ones from the other swap types.
> Allow incoming chain swap refund tx id overwrite

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/chain_swap.rs
This PR increases the number of retries on all onchain fetching methods that use retries and were retrying less than 10 times. 
I noticed in the wild that while processing a chain swap LockupFailed event, we were setting the status to `Failed` instead of `Refundable` because we would fail to find the user lockup in the 5 retries that were attempted. This should hopefully reduce the likelihood of this kind of issues.
> Increase onchain fetching retries

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/wallet.rs
When testing various connections issues I have noticed that the electrum connection hangs when switching network and sometimes also  after hibernation.
This turned out to be the misconfigured timeout value (OS default which was undefined).
In order to set the timeout we needed to upgrade lwk_wallet dependency (@dangeross  I cherry picked your scan PR on top).
Using this PR the connection recovers immediately. 
I also forked lwk_wallet into breez organization.
> configure timeouts

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
- lib/core/src/chain_swap.rs
- lib/core/src/receive_swap.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils/chain.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/receive_swap.rs
- lib/core/src/test_utils/recover.rs
- lib/core/src/test_utils/sdk.rs
- lib/core/src/test_utils/send_swap.rs
Previously we had a lock wrapping the liquid chain service. This caused every endpoint that was called to block other endpoints. For example when the recoverer from the realtime sync fetching script history (which may take several seconds) was blocking a manual user Sync calls that use the same chain service and both were blocking other endpoint such as rescan_chain_swaps.
This PR removes that lock and only apply a lock internally on the tip endpoint since it is the only one that is mutable.
A dedicated tip_client is used for that as the alternative of creating electrum connection for each tip call is more expensive:
* cached electrum tip: ~70 ms
* new electrum tip: ~600 ms
Edit:  Applied the same approach also for bitcoin chain service.
Another significant bottleneck was …
> Lock free chain service

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
ElecturmClient needs to be initialized with the current tip which forced us to query right on start which caused up to several seconds of sdk initialization.
Since we don't really need lwk ElectrumClient to use electrum this PR shifts to use the underline Client directly and saves this startup time and reduced it to less than a millisecond. 
Edit: It turns out that also Electurm client initialization has some overhead as it tries to connect. I changed the code to use lazy initialization of electrum which causes the startup flow to complete instantly now.
> Remove electrum tip query on start

- cli/src/commands.rs
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/SwapUpdated.kt
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #636 
This PR prevents a potential issue where notifications might be missed due to the SDK instance of a backgrounded app still being able to issue an event. Changes:
- Adds the swap id hash as a possible identifier for the `get_payment` method
- Exposes the claim tx id in payments to allow determining if the claim has been broadcasted
- Notification plugins, in addition to listening to events, now also poll the payment state
- With the app in the background, payment notifications should work reliably without missed or duplicate notifications
- Lightning payments
- Onchain payments
> Prevent missing notifications due to concurrent SDK instances

- lib/core/src/chain/bitcoin.rs
- lib/core/src/chain/liquid.rs
Until we have proper redundancy of chain services the tip endpoint that is used frequently may fail if electrum is not responsive or disconnected which is likely to happen in mobile environment.
This PR brings back the previous behavior where we keep the last known tip and return it on error.
> Cache last known tip

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
This switches the AES implementation used by `ecies` from OpenSSL to "pure", which should help circumvent issues we see when running the SDK on iOS.
We should keep in mind the penalty we incur with this change: https://docs.rs/ecies/latest/ecies/#benchmark.
I've tested that decrypting old records that were created with the openssl version does work correctly.
> Switch to pure AES implementation in ecies

- lib/core/src/sdk.rs
- lib/core/src/utils.rs
This PR:
- Adds a log on initialization, moving it from the previous `start` method (which only tracked the background thread starting, meaning < 1ms) to the actual `connect` method
- Adds a logo, along with relevant information about the SDK (including the version, which is useful for debugging external logs). 
**Note:** Not sure whether Cargo respects the `CARGO_PKG_VERSION` env variable when using the SDK as a rust dependency. Will test and update.
**Note:** If the logo is overkill we can just log the start time and version, just thought it would be a nice addition. This is how it looks like on the logs:
```
[2025-02-05 03:51:43.927 INFO breez_sdk_liquid::utils:151]                                               
↘↘↘↘↘↘↘↘       
↘↘↘↘↘↘↘↘    
↘↘↘↘↘       ↘↘↘↘   
↘↘↘      Breez SDK …
```
> Misc: Add log header on SDK initialization

- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
Resolves #699
This PR changes chain data payment sync to use the same liquid wallet tx set for swap recovery and liquid payment recovery, preventing a liquid claim tx from only being included in the set used for liquid payment recovery, causing it to be misplaced for an incoming liquid payment.
- No duplicate payments are shown in any part of an incoming Lightning payment lifecycle. This applies both to a local instance of the SDK (where the swap was created) as well as a concurrent instance that syncs the incoming payment.
> Use same tx_map for recovery of swaps and liquid payments

- lib/core/src/wallet.rs
Turns out lwk wallet sometimes returns general persist error when one of the internal folders doesn't exist.
This leads to an unrecovered error on sdk initialization.
> fix persist error on initialization

- lib/core/src/sdk.rs
- lib/core/src/sync/client.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/client.rs
- lib/core/src/sync/proto/sync.proto
- lib/core/src/test_utils/sync.rs
Reflects changes from breez/data-sync@34e551c5cfe1.
This PR adds a notification endpoint `ListenChanges`, which triggers the real-time sync event loop whenever the remote broadcasts a notification through a gRPC stream.
**Testing note:**
Testing this PR is similar to repeating the initial tests for real-time sync. We need to ensure that the payment details fields get populated every time another instance pays. Furthermore, the delay between payment syncs should now be reduced, so you should see the payment appear on both devices much quicker.
> Real-time Sync: Add notifications endpoint

- cli/Cargo.lock
- cli/Cargo.toml
- lib/Cargo.lock
- lib/bindings/Cargo.toml
- lib/core/Cargo.toml
This reverts commit c52acd5ae7e2ce8544750ab53b044173cc228002.
This fixes the tls issue that was introduced and causes pending payments (unclaimed) because network requests to the swapper fails.
> Revert "Clean and update dependencies (#726)"

- lib/core/src/persist/address.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/mod.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/persist/sync.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
This PR fixes some issues found in send swap recovery:
1.  Fixes an issue where the lockup tx is seen as the claim tx if the non-local wallet has not yet seen the lockup tx (its not in the tx_map)
2. Fixes an issue where the non local swap has not yet had time to recover (is in state Created) and the SDK is restarted (set to TimedOut and no longer monitored)
1.  Not directly testable, nothing occurs in the UI
2.  Previously the issue is seen on the non-local device where the send swap is always shown as a liquid payment. 
- Send a lightning payment on the local device
- On the non-local device wait for the liquid payment
- Force quit the app
- Reopen and check if the payment swap data recovers
> Send Swap recovery fixes

- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
This addresses part of #725 by adding a stale payment tx data cleanup. 
The idea is to look for pending payment txs that the liquid wallet does not recognize and delete them if they are older than a certain grace period (to allow for tx propagation through the network).
> Clean payment txs data on sync

- lib/core/src/persist/chain.rs
- lib/core/src/persist/send.rs
Partially fixes #729 although it still may well be that the payment appears as a Liquid payment briefly
> Consider created send swaps as recoverable

- lib/core/src/chain_swap.rs
- lib/core/src/model.rs
- lib/core/src/persist/chain.rs
- lib/core/src/persist/migrations.rs
- lib/core/src/persist/receive.rs
- lib/core/src/persist/send.rs
- lib/core/src/persist/sync.rs
- lib/core/src/receive_swap.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
- lib/core/src/sync/model/data.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/persist.rs
Partly addresses #725.
This PR prevents clearing swap tx ids that we potentially broadcast for a certain grace period after the last update, only for local swaps.
Changes:
- Encapsulated metadata fields like the existing `index` and the new `last_updated_at` in a new `SwapMetadata` struct
- Added the `is_local` boolean to the metadata struct, removing the need to query it separately 
- When within the grace period, prevent clearing tx id of txs we potentially broadcasted
- Dropped the tx propagation grace period from 3 minutes to 30 secs since our electrum no longer has issues providing txs that are in the mempool
> Add tx propagation grace period to swap recovery

- cli/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/client.rs
- lib/core/src/sync/proto/sync.proto
This PR makes sure that we're not running the event loop when we're the broadcasters of a record.
**Note:** If the record is pulled (non-local), even if we're the ones broadcasting the changes on top we'll still execute the flow. This only applies when we're the initiators.
@roeierez **Explanation:** The reason for omitting `new_revision` from the `Notification` object is that we run into a race condition between the remote listener and push threads. The notification from the remote may be received before we persist the pushed record (and its state), so we need to `lock_outgoing_record` before pushing, using a mock revision. Since we then have a mock revision there would be no need to compare that with the notification's `new_revision` field.
> Real-time Sync: Avoid running event loop on local changes

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/receive_swap.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #734.
This removes the min 0-conf fee rate. Given that, for now, Liquid blocks are practically empty, there is no need to check the fees. If, in the future, a fee market develops, we would want the minimum 0-conf fee rate to depend on current fee conditions, so the current solution wouldn't be helpful.
> Remove min 0-conf fee rate

- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
Fixes #741 
This PR 
- Uses the invoice's `description` first; if it's empty, falls back to extracting the `description` from `metadata_str` as the `description` value saved to `PaymentTxDetails`.
- Fixes how `description` is persisted for LNURLp payments, as the `description` value saved to `PaymentTxDetails` was previously ignored by the persister.
> Extract `description` from `metadata_str` for LNURL payments

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
This PR upgrades the following dependencies:
- `rusqlite` > https://github.com/Spxg/rusqlite/commit/06917a785e312fb822de7654922c198504a8cb46 (can switch back to main once rusqlite/rusqlite#1643 is merged)
- `rusqlite_migraiton` > https://github.com/hydra-yse/rusqlite_migration/commit/acbdc59315dedd10f004fd031de63cb0e27bbb26 (will wait for the merge above and then open a PR in `rusqlite_migration` and `tokio-rusqlite` respectively)
This allows us to cross compile the `rusqlite` crate to WASM while also ensuring it works.
> WASM: Switch to compatible `rusqlite` fork

- lib/core/src/recover/recoverer.rs
- lib/core/src/send_swap.rs
- lib/core/src/test_utils/wallet.rs
- lib/core/src/wallet.rs
This PR:
- Ensures the wallet and chain service tips are aligned (with 3 block leeway) when calling the `recover_from_onchain` method
- Ensure the error is handled properly depending on the caller:
1. Real-time sync: We want to throw an error and retry on next event loop
2. SDK sync loop: We want to handle the error gracefully and ensure we are not disabling event notifications
> Recovery: Ensure wallet and chain service tips are within leeway

- .github/workflows/main.yml
- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
- lib/core/Cargo.toml
This PR:
- Bumps reqwest to 0.12.13 via https://github.com/breez/breez-sdk-greenlight/pull/1177
- Separates out WASM CI jobs to improve reviewability
> Improve WASM CI tests

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain_swap.rs
- lib/core/src/model.rs
- lib/core/src/receive_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/boltz/status_stream.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/status_stream.rs
- lib/core/src/test_utils/swapper.rs
This PR upgrades the boltz client dependency to the updated version proposed in https://github.com/SatoshiPortal/boltz-rust/pull/91.
Besides updating the dependency, it also starts using it for connecting the status stream websocket. The updated boltz client uses `tokio-tungstenite-wasm` for websockets, which doesn't expose pinging. To address this Boltz now supports application-level ping messages, which the boltz client PR also exposes.
Because now the boltz client is used to start the websocket connection, I've merged the `BoltzStatusStream`struct into `BoltzSwapper`, which now also implements `SwapperStatusStream`.
The electrum client is still kept in use. Supporting WASM will require using esplora, which I propose we address in a follow-up PR.
> WASM: Update boltz client dependency and use included wasm tokio-tungstenite

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain/liquid.rs
- lib/core/src/model.rs
- lib/core/src/recover/handlers/handle_chain_receive_swap.rs
- lib/core/src/recover/handlers/handle_chain_send_swap.rs
- lib/core/src/recover/handlers/handle_receive_swap.rs
- lib/core/src/recover/handlers/handle_send_swap.rs
- lib/core/src/recover/handlers/mod.rs
- lib/core/src/recover/handlers/tests/handle_chain_receive_swap_tests.rs
- lib/core/src/recover/handlers/tests/handle_chain_receive_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_chain_send_swap_tests.rs
- lib/core/src/recover/handlers/tests/handle_chain_send_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_receive_swap_tests.rs
- lib/core/src/recover/handlers/tests/handle_receive_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_send_swap_tests.rs
- lib/core/src/recover/handlers/tests/handle_send_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/mod.rs
- lib/core/src/recover/mod.rs
- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/chain.rs
- lib/core/src/test_utils/send_swap.rs
Work in progress.
Instead of letting the recoverer handle all kind of hash tables tailored maid for each swap, it is only responsible for fetching the script histories (and transactions) from the chain services, passing it as context to the specific swap recover handler and let it doing all the matching work at the low level.
Still need to do a lot of testing and changes before it is ready.
Pushing it to get feedback on the concept.
> Refactor recoverer

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/core/src/sdk.rs
- lib/wasm/src/model.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR fixes a couple of LNURL related issues:
- Fixes a regression where LNURL-pay drain no longer worked (failed in the prepare step)
- Adds the LNURL info and BIP353 address to Liquid payment details so they are also available when paying via MRH
See https://github.com/breez/misty-breez/issues/422
- LNURL-pay drain should work
- LNURL info should be displayed in the payment when paying via LNURL-pay / lightning address to another Misty/SDK app
**Not-testable testing notes:**
- BIP353 address (as Lightning Address) should be displayed in the payment when paying to another Misty/SDK app and the BIP353 address links to a LNURL-pay.
> Fix LNURL drain and payment info

- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ForegroundService.kt
This PR dismisses on Android the replaceable notifications when the background task / service is shutdown
Fixes #767 
- When receiving via LNURL/lightning address, the "Receiving payment information" / "Fetching invoice" should be dismissed automatically once the background task is closed. This can be tested by sending via lightning address between two Misty devices (receiving on Android).
> Notification Plugin: Dismiss replaceable notifications on service shutdown

- .github/workflows/build-language-bindings.yml
- .github/workflows/main.yml
- .github/workflows/publish-all-platforms.yml
- .github/workflows/publish-android.yml
- lib/bindings/langs/android/lib/build.gradle.kts
- lib/bindings/langs/kotlin-multiplatform/breez-sdk-liquid-kmp/build.gradle.kts
- lib/bindings/makefile
- packages/flutter/README.md
- packages/flutter/android/build.gradle
- packages/flutter/android/build.gradle.production
- packages/react-native/android/build.gradle
- packages/react-native/example/android/build.gradle
This PR reverts UniFFI upgrade to 28.0 for Android builds introduced on  #766.
- [Downgrade android release to Uniffi 0.25](https://github.com/breez/breez-sdk-liquid/pull/786/commits/2e339df97cc0b5c7db79c985a8d8e4b75cf0ccfa)
- Bump JNA used on bindings tests to 5.14.0
- Bump package requirements on `flutter_breez_liquid` `README.md`
> Downgrade android release to Uniffi 0.25

- lib/core/src/lib.rs
This locks out the flutter-specific modules on WASM builds
> WASM: lock frb and bindings modules

- .github/workflows/main.yml
- Makefile
- lib/core/Makefile
This adds a makefile to the `core` crate with helper targets for running clippy and tests. We already have something similar on the wasm crate, but running tests there won't run the tests in the core crate. I also adjusted the main makefile to run wasm clippy and tests on both crates.
> WASM: run core crate tests on wasm

- lib/wasm/src/model.rs
This PR adds the missing lnurl_info & bip353_address fields to the wasm PaymentDetails::Liquid enum
> WASM: Add missing lnurl_info/bip353_address to wasm PaymentDetails

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/.gitignore
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #778.
This exposes a new event for when a real-time data sync occurs. The primary motivation is to allow showing users some visual indication on startup that this sync is occurring (so payments might be missing). Integrators know when the rt sync is complete through the new event. Also included in the event indication if new data was pulled or not, which may allow integrators to provide users with feedback that data is coming in from other devices.
Misc: renamed the existing `Synced` event to `ChainSynced` to allow better distinction between both synced events.
> Expose real time synced event

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/status_stream.rs
- lib/core/src/sync/mod.rs
- lib/core/src/test_utils/status_stream.rs
This PR proposes using [`tokio_with_wasm`](https://crates.io/crates/tokio_with_wasm) to spawn async tasks on wasm. 
Something to keep in mind is https://crates.io/crates/tokio_with_wasm#caution. The most obvious and immediate effect is that our tests that rely on spawning a task ( the update tracking tests on `sdk.rs`), if they fail on WASM, they do with a very non-descriptive error. A failing assert in just one of the tests causes the following output. We don't even get to see which test failed. We might deem this fine if we think it's unlikely for wasm tests to fail differently from native tests.
```
Failed to detect test as having been run. It might have timed out.
output div contained:
running 38 tests
test sdk::tests::test_zero_amount_chain_swap_with_leeway ... ok
test …
```
> WASM: spawn task

- lib/bindings/langs/flutter/justfile
Locks the installation of `cargo-expand` until an update to `plist` is released. See https://github.com/ebarnard/rust-plist/pull/152
Fixes #802
> Lock cargo-expand install

- .github/workflows/build-bindings-android.yml
- .github/workflows/build-bindings-windows.yml
- .github/workflows/publish-csharp.yml
- .github/workflows/publish-golang.yml
- .github/workflows/publish-python.yml
- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
- lib/bindings/langs/csharp/src/Breez.Sdk.Liquid.csproj
- lib/bindings/makefile
- lib/core/src/sdk.rs
- lib/core/src/utils.rs
Uses the updated `rust-lightning` dependency in https://github.com/breez/breez-sdk-greenlight/pull/1186 to build for 32bit targets
CI publish test: https://github.com/breez/breez-sdk-liquid/actions/runs/14045179367
> Reintroduce 32bit builds

- lib/bindings/langs/flutter/scripts/version.sh
- packages/flutter/pubspec.yaml
This change ensures the Flutter plugin always references the correct version of the Dart plugin.
This is preliminary work for publishing the plugins on pub.dev.
> Update Flutter plugin to match Dart plugin version

- lib/core/Cargo.toml
- lib/core/src/error.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/wallet.rs
This PR:
- Adds tokio-stream to the wasm dependencies (previously was only available on non-wasm)
- Replaces Send + Sync with MaybeSend + MaybeSync where needed
- Fixes an unused warning 
- Excludes the implementation of `From<UrlError>` on Wasm
> WASM: fix various minor issues

- cli/README.md
This PR improves the `README` by adding instructions on setting the `BREEZ_API_KEY` before running cargo run. This ensures users know they need an API key and how to set it up properly.
**Changes Implemented**:
✅ Added instructions on setting `BREEZ_API_KEY` for Linux, macOS, and Windows.
✅ Included a link to request an API key from Breez.
✅ Clarified that the API key is required before running the CLI.
> Update README: Add Breez API Key Instructions

- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/receive_swap.rs
- lib/core/src/test_utils/sdk.rs
- lib/core/src/test_utils/send_swap.rs
- lib/core/src/wallet.rs
- lib/wasm/src/lib.rs
- lib/wasm/src/model.rs
This PR:
- Manually maps the `default_config` method (which is now feature-locked on sdk-core) to use the config's esplora branch
- Adds the `DataSynced` event to `SdkEvents`
- Removes `BlockchainExplorer::Electrum` from pattern matches
> WASM: Fix minor compilation issues

- lib/core/src/chain/bitcoin/electrum.rs
- lib/core/src/chain/liquid/electrum.rs
- lib/core/src/model.rs
- lib/core/src/swapper/boltz/client.rs
- lib/core/src/wallet.rs
This PR:
- Adds support for using Esplora on LWK wallet full scan
- Reorganizes electrum client initialization options in the configuration for dedup
> Add Esplora support to LWK wallet

- .github/workflows/publish-swift.yml
- lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/ios-arm64/breez_sdk_liquidFFI.framework/Info.plist
- lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/ios-arm64_x86_64-simulator/breez_sdk_liquidFFI.framework/Info.plist
- lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/macos-arm64_x86_64/breez_sdk_liquidFFI.framework/Info.plist
The lack of a `CFBundleShortVersionString` key in the framework Info.plist files are causing issues in newer Xcode versions. This PR sets the version from the publishing package version
Dummy [breez_sdk_liquidFFI.xcframework](https://github.com/breez/breez-sdk-liquid/actions/runs/14123021249/artifacts/2836876495) from CI run
Fixes #825
> Set Swift framework CFBundleShortVersionString

- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/boltz/status_stream.rs
Closes #839
This PR:
- Renames Boltz swapper fields (`client` to `boltz_client`, for clarity)
- Uses `OnceLock` for both the swapper's Bitcoin and Liquid client, to avoid hanging on connect
> Use lazy initialization for all swapper clients

- lib/core/src/chain/bitcoin/esplora.rs
- lib/core/src/chain/liquid/esplora.rs
- lib/core/src/sdk.rs
This PR fixes some additional uses of tokio sleep and getting the current time that we didn't spot before. It applies the same strategies that we are currently using in the rest of the codebase.
- The esplora clients use a sleep to retry requests after a delay. Fixed using `tokio_with_wasm`.
- The `is_expired()` method of `Bolt11Invoice` internally uses `std::time::SystemTime::now()`. Replaced it with an implementation that relies on `web_time.`
> WASM: fix remaining sleep and current time uses

- .github/workflows/main.yml
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/DEVELOPMENT.md
- lib/core/Makefile
- lib/core/src/model.rs
- lib/core/tests/mod.rs
- lib/core/tests/regtest/bitcoin.rs
- lib/core/tests/regtest/bolt11.rs
- lib/core/tests/regtest/liquid.rs
- lib/core/tests/regtest/mod.rs
- lib/core/tests/regtest/utils.rs
- regtest/docker-compose.yml
- regtest/proxy/Dockerfile
- regtest/proxy/requirements.txt
- regtest/proxy/ssl_proxy.py
Works towards #635
This PR:
- Adds an initial set of regtest tests that covers the different kinds of payments the SDK supports
- Adds a proxy to the regtest setup to allow control of the nodes when running the tests on Wasm (full wasm support is out of scope for this PR). The proxy is useful to circumvent issues caused by browser restrictions on TLS certificates and CORS policies.
- Sets up CI jobs to run the tests separately
> Add regtest end-to-end tests

- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
- lib/core/src/sdk.rs
As Interval MissedTickBehavior is not available for Wasm, after the sync we reset the interval to ensure there is a gap before the next sync.
This PR also updates the lightning dependency to 0.1.2 
Fixes #857
> Wasm: Reset interval after sync

- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/lib.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/core/src/test_utils/chain.rs
- lib/core/src/test_utils/chain_swap.rs
- lib/core/src/test_utils/mod.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/test_utils/receive_swap.rs
- lib/core/src/test_utils/sdk.rs
- lib/core/src/test_utils/send_swap.rs
- lib/core/src/test_utils/status_stream.rs
- lib/core/src/test_utils/swapper.rs
- lib/core/src/test_utils/sync.rs
- lib/core/src/test_utils/wallet.rs
- lib/wasm/Cargo.toml
- lib/wasm/Makefile
- lib/wasm/src/backup/indexed_db.rs
- lib/wasm/src/backup/mod.rs
- lib/wasm/src/backup/node_fs.rs
- lib/wasm/src/lib.rs
- lib/wasm/src/utils.rs
- packages/wasm/README.md
- packages/wasm/examples/node/.gitignore
- packages/wasm/examples/node/src/cli.js
Resolves #836
This adds a db backup mechanism on WASM by persisting the db on every sync (every 10 secs) and when new records are pulled from the real time data sync. We may reduce the frequency, but it seems to me like the overhead is negligible. May become significant in instances with a very large payment history, but we can adjust it later. I added a log to check how long it takes to create a backup so that we can track it. 
Persistence is done using [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) on the browser and the [fs](https://nodejs.org/api/fs.html) API on node.js. Other runtimes won't support backups, but we may add support in the future.
> WASM: db backups

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/wallet.rs
This PR is based on a [forked version of waterfalls](https://github.com/breez/waterfalls/tree/savage-to-derivation-index) that would (temporarily) need deploying
(Resolved by the `/address/<addr>/txs` request being processed by esplora)
Fixes #844
> LWK waterfalls fixes

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
Updates LWK to use wateralls to fetch scripts history (See PR https://github.com/Blockstream/lwk/pull/80).
~Calling `/v2/waterfalls?addresses=` suffers the same issue as calling `/address/<addr>/txs` in waterfalls, in that it only returns a subset of the results esplora does (missing txs in script history). So setting this PR to draft while we determine if that is the intended behavior.~
Fixes #855
> Waterfalls script history

- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain/bitcoin/esplora.rs
- lib/core/src/chain/liquid/esplora.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/client.rs
- lib/core/src/test_utils/swapper.rs
- lib/core/src/wallet.rs
~Waiting for breez/server#67~
This PR:
- Adds API key check for Breez waterfalls url on all client types (chain, wallet, swapper)
- Changes the main Esplora url to Breez instance
- Switching to [custom branch](https://github.com/hydra-yse/boltz-rust/tree/esplora-custom-client) until SatoshiPortal/boltz-rust#100 is merged
> Switch Esplora client url to Breez server instance

- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
Strip ₿ prefix from input before BIP353 lookup
@erdemyerebasmaz do you want this cherry picking to the `misty-release` branch?
> Strip input prefix before bip353 lookup

- cli/Cargo.lock
- lib/core/src/model.rs
- lib/core/src/recover/handlers/handle_send_swap.rs
- lib/core/src/recover/handlers/tests/handle_send_swap_tests.rs
- lib/core/src/recover/handlers/tests/handle_send_swap_tests_integration.rs
- lib/core/src/sdk.rs
- lib/core/src/send_swap.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/test_utils/persist.rs
- lib/core/src/test_utils/swapper.rs
This PR incorporates the [minimal_batched submarine pair limit](https://github.com/SatoshiPortal/boltz-rust/pull/99) to allow batched send swap payments, where in the case of a batched payment there is no need to cooperatively claim.
This lowers the minimum send payment amount to around 21 sats. 
- Pay invoices (from non-SDK apps) between 21 - 999 sats. Should complete and have a valid preimage.
- Pay invoices (from non-SDK apps) 1000 + sats. Should complete and have a valid preimage.
> Handle send swap minimal_batched

- lib/wasm/src/platform/browser/wallet_persister.rs
- lib/wasm/src/platform/mod.rs
- lib/wasm/src/platform/wallet_persister_common.rs
This PR addresses an issue where loading wallet cache updates on the browser would fail with `Missing update on index <index>`, which could happen if there are concurrent SDK instances. If one of the instances cleared the cache, the other would not notice and would continue to persist updates, thus introducing gaps.
This adds prevention by making sure an update only persists if there are no gaps in the persisted updates and also gracefully handles the gaps if, for any reason, they still happen.
> Wasm: prevent IndexedDb wallet cache corruption and gracefully handle it

- lib/core/src/wallet/mod.rs
- lib/core/src/wallet/persister.rs
- lib/wasm/src/platform/browser/wallet_persister.rs
- lib/wasm/src/platform/node_js/wallet_persister.rs
- lib/wasm/src/platform/wallet_persister_common.rs
This fixes a bug introduced in #868, where on native builds clearing the cache would be followed by:
```
ERROR breez_sdk_liquid::sdk:429] Failed to connect: No such file or directory (os error 2)
```
The `clear_cache` implementation of `FsWalletCachePersister` deleted the cache directory and it was never created again. Given that the cache directory is defined and created by the constructor of lwk's `FsPersister`, I propose we construct that struct again instead of trying to create the dir ourselves.
> fix: missing wallet cache dir creation after deletion

- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/status_stream.rs
- lib/core/src/test_utils/sync.rs
- lib/core/tests/regtest/bitcoin.rs
- lib/core/tests/regtest/bolt11.rs
- lib/core/tests/regtest/liquid.rs
- lib/core/tests/regtest/mod.rs
The `Interval` from [`tokio_with_wasm`](https://docs.rs/tokio_with_wasm/latest/tokio_with_wasm/) causes a panic on node.js. 
This PR proposes fixing it by simply not using Interval and using sleep instead. I did try [`wasmtimer`](https://github.com/whizsid/wasmtimer-rs), which at first seemed like it provided a good Interval implementation, but I later realized it was buggy: using it prevented the shutdown branches from ever being picked up.
I'm of course open to ideas/alternatives where tasks are still started at regular intervals
> fix: Interval not compatible with node.js

- lib/core/src/persist/sync.rs
- lib/core/src/sync/mod.rs
- lib/core/src/sync/model/client.rs
- lib/core/src/sync/model/mod.rs
This PR:
- Improves logging for the real-time sync service (prefixing, log level and messages)
- Adds a failsafe mechanism in case of consecutive errors while running the event loop (> 5). After too many failed attempts, it will wipe the sync tables (incoming, outgoing and state) and re-enqueue all local swaps for push.
- Improves error handling with new `PushError` and `PullError` variants (reflected in logs)
> Add failsafe mechanism for real-time sync

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/chain_swap.rs
- lib/core/src/receive_swap.rs
- lib/core/src/swapper/boltz/bitcoin.rs
- lib/core/src/swapper/boltz/client.rs
- lib/core/src/swapper/boltz/liquid.rs
- lib/core/src/swapper/boltz/mod.rs
This PR addresses a race condition where concurrent attempts to claim the same swap (both Chain Swaps and Receive Swaps) could lead to failures when interacting with the Boltz backend. The server initiates a session when each claim is started, so when a second claim is initiated in quick succession (before the signature is submitted), the first session is dropped, causing the submitted partial signature to be considered invalid.
The proposed fix is to introduce in-memory locking. There is an edge case where a panic may cause a lock to be held until restart, but this is unlikely (a panic on either the sync or the status stream tasks would be a big issue itself), so IMO it's acceptable.
> Prevent concurrent claim attempts

- packages/flutter/android/build.gradle
- packages/flutter/android/build.gradle.production
- packages/flutter/ios/flutter_breez_liquid.podspec
- packages/flutter/ios/flutter_breez_liquid.podspec.production
- packages/flutter/macos/flutter_breez_liquid.podspec
- packages/flutter/macos/flutter_breez_liquid.podspec.production
The recent commit bumping to 0.8.0 missed updating the flutter package versions and CI was complaining.
> Fix missing 0.8.0 version bump

- .github/workflows/main.yml
- .gitmodules
- lib/core/Cargo.toml
- lib/core/DEVELOPMENT.md
- lib/core/Makefile
- lib/core/src/lib.rs
- lib/core/src/model.rs
- lib/core/src/utils.rs
- lib/core/tests/regtest/bitcoin.rs
- lib/core/tests/regtest/bolt11.rs
- lib/core/tests/regtest/liquid.rs
- lib/core/tests/regtest/mod.rs
- lib/core/tests/regtest/utils.rs
- regtest/docker-compose.yml
- regtest/waterfalls-service/Dockerfile
- regtest/waterfalls-service/nginx.conf
Resolves #635 
This PR adds support for WASM to the end-to-end test suite. Changelist:
- Splits up tests into electrum and esplora variants and runs only the esplora ones on Wasm.
- Upgrades the data-sync regtest instance to include https://github.com/breez/data-sync/pull/22
- Sets up waterfalls + nginx on regtest
- Drops `start_pay_invoice_lnd` (it was unnecessary)
Known issues / potential improvements:
- There are some issues with events missing, which I propose to deal with in a later PR (#847)
- The waterfalls instance is built from scratch on every CI run. It would be nice to avoid this to reduce jobs times. #892
> WASM: end-to-end-test support

- .github/workflows/publish-flutter.yml
- lib/bindings/langs/flutter/scripts/version.sh
- packages/flutter/android/build.gradle
- packages/flutter/android/build.gradle.production
- packages/flutter/ios/flutter_breez_liquid.podspec
- packages/flutter/ios/flutter_breez_liquid.podspec.production
- packages/flutter/macos/flutter_breez_liquid.podspec
- packages/flutter/macos/flutter_breez_liquid.podspec.production
- packages/flutter/pubspec.yaml
The `ref` for the breez_liquid dependency was missing the "v" of the repo tag causing:
```
Because every version of flutter_breez_liquid from git depends on breez_liquid from git which doesn't exist (Could not find git ref '0.8.0' (fatal: ambiguous argument '0.8.0')
```
> Fixes the reference to the dart repo tag

- lib/core/src/sdk.rs
Moving over to waterfalls, which we already use on Wasm builds, provides significant performance benefits.
> Set esplora/waterfalls as default chain explorer backend

- lib/core/src/sdk.rs
This PR:
- Increases the `NETWORK_PROPAGATION_GRACE_PERIOD` to 1 minute, to allow unconfirmed Send swaps to complete before deleting their associated `PaymentTxData`
- Aborts the `sync_inner` method when the wallet scan fails, so that operations that depend on the scan (e.g. recovery) won't execute unpredictably
> Fix ignored payment events on failed wallet sync

- .github/workflows/build-bindings-android.yml
- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/InvoiceRequest.kt
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/InvoiceRequest.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/bindings.rs
- lib/core/src/error.rs
- lib/core/src/frb_generated.rs
- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/boltz/status_stream.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/status_stream.rs
- lib/core/src/test_utils/swapper.rs
- lib/core/tests/regtest/bolt11.rs
- packages/dart/lib/src/bindings/duplicates.dart
- packages/dart/lib/src/bindings/duplicates.freezed.dart
- packages/dart/lib/src/error.dart
- packages/dart/lib/src/error.freezed.dart
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
This PR:
- Sends the BOLT12 invoice request error immediately back via websocket or webhook response
- Removes setting the BOLT12 invoice blinded payment path to the MRH short channel id
- Uses the MRH returned alongside fetching the BOLT12 invoice to send directly via Liquid tx
- Optimizes requests to Boltz during invoice creation (remove request to get CLN node public key, parellelize requests to get BOLT12 params and reverse swap pairs)
- When paying under the minimum receive amount (< 100sat) from Phoenix, you should receive a payment failure error faster. Test Misty when both in foreground and background
Builds:
- Android 432: https://github.com/breez/misty-breez/actions/runs/14836581663
- iOS TestFlight 6418.1: …
> BOLT12 receive updates

- lib/core/src/sdk.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/bolt12_offer.rs
- lib/core/src/test_utils/swapper.rs
This PR sets the BOLT12 offer minimum amount to the receive payment minimum limit (currently 100sat). When setting the minimum a description needs to be set also, which can be done using the `description` param of `ReceivePaymentRequest`
Misty PR: https://github.com/breez/misty-breez/pull/537
- Using either the BOLT12 offer or BIP353 address, send a payment using the **latest** Phoenix. Edit the amount (set default to the minimum amount). Check the description is set (in Misty it's "Pay to Misty Breez")
**Builds:**
- Android: https://github.com/breez/misty-breez/actions/runs/15036725919
- iOS 6426.1: https://github.com/breez/misty-breez/actions/runs/15036727917
> Set the BOLT12 Offer min amount

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/wasm/src/model.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
When:
- Sending the `claim_tx_id` is the Bitcoin txid
- Receiving the `lockup_tx_id` is the Bitcoin txid
Fixes #916
> Add user lockup_tx_id to Bitcoin payment details

- cli/src/commands.rs
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/sdk.rs
- lib/core/src/utils/mod.rs
- lib/wasm/src/model.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Enables BOLT12 drain by inverse calculating the receiver amount the same way as LNURL-pay. We also add the `PayAmount` to the prepare responses to allow them to be used in when sending to determine if the request was a drain.
- Re-test draining via LNURL/lightning address to SDK/non-SDK devices
- Test draining via BOLT12 Offer/BIP535 address to SDK/non-SDK devices
Fixes #922 
Fixes https://github.com/breez/misty-breez/issues/544
> Rework draining to enable BOLT12 drain

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
Fixes the issue where LWK panics if an async sleep is triggered in node.js because it depends on web_sys::Window
LWK commit: https://github.com/breez/lwk/commit/417405cabbebe89df758fe7990f80011808aff4e
> Update LWK for node.js compatible sleep

- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/src/frb_generated.rs
- lib/core/src/model.rs
- lib/core/src/persist/mod.rs
- lib/core/tests/regtest/bitcoin.rs
- lib/wasm/src/model.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
Resolves #913
This exposes `bitcoin_address` in `PaymentDetails::Bitcoin`. The goal is to allow integrators to match created receive chain swaps with the resulting payment.
I opted for exposing just the address (not the bip21) as it is simpler and keeps the field consistent across payment directions.
> Expose bitcoin destination address

- lib/core/src/sdk.rs
Despite it being very rare, I've just seen logs from version 0.9.0 (it uses the current grace period) where the period wasn't long enough for us to see a receive swap claim tx in time before we cleared it from the swap. This, in turn, caused temporary payment duplication. In this specific case, the claim tx was seen ~10 seconds after it was cleared. 
Probably 90 secs would be enough, but I propose to set it to 120 secs to be on the safe side. Only downside of a larger number is that we increase the time it takes for a txid to be cleared in case its broadcast failed + we fail to update the db accordingly, which IMO is fine given the unlikelihood of such an occasion.
> Increase network propagation grace period

- cli/src/main.rs
- cli/src/persist.rs
This adds a convenient argument to the CLI that allows specifying which phrase file name is used. Not providing one keeps the same default.
> CLI: Add phrase file arg

- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPayVerify.kt
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/LnurlPayVerify.swift
LUD-21 seems to go against the convention of other LUDs that non-empty responses don't need an explicit `status` field set to `OK`, so we set one for this LUD.
Fixes https://github.com/breez/misty-breez/issues/564
> Explicitly set status OK in the LNURL verify response

- cli/Cargo.lock
- lib/Cargo.lock
- lib/Cargo.toml
- lib/core/Cargo.toml
- lib/core/src/model.rs
- lib/core/src/swapper/boltz/mod.rs
- lib/core/src/swapper/boltz/proxy.rs
- lib/core/src/swapper/boltz/status_stream.rs
- lib/core/src/swapper/mod.rs
- lib/core/src/test_utils/swapper.rs
This PR sets up authentication for the swap proxy.
Changes:
- Boltz client is updated to allow use of a custom reqwest client
- [sdk-common is updated](https://github.com/breez/breez-sdk-greenlight/pull/1231) to provide both the boltz url and proxy url. When an api key is available, the proxy url is used.
- When using our swap proxy:
- The api key is added to the headers of http requests
- The api key is sent as the first message when connecting to the status stream ws. See https://github.com/breez/swapproxy/pull/10.
> Set api key on boltz client requests

- lib/core/src/model.rs
- lib/core/src/sdk.rs
The "valid" makes the error message confusing, as it may be interpreted as if an api key was provided, but it was invalid.
> Clarify no api key error messages

- lib/core/src/model.rs
- lib/core/src/persist/cache.rs
- lib/core/src/persist/chain.rs
- lib/core/src/recover/handlers/handle_chain_receive_swap.rs
- lib/core/src/recover/handlers/handle_chain_send_swap.rs
- lib/core/src/recover/handlers/handle_receive_swap.rs
- lib/core/src/recover/handlers/handle_send_swap.rs
- lib/core/src/recover/handlers/tests/handle_chain_receive_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_chain_send_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_receive_swap_tests_integration.rs
- lib/core/src/recover/handlers/tests/handle_send_swap_tests_integration.rs
- lib/core/src/recover/model.rs
- lib/core/src/recover/recoverer.rs
- lib/core/src/sdk.rs
This PR:
- Optimizes fetching of the Bitcoin tip by only doing it if the SDK knows of any chain swap
- Gracefully handles Bitcoin tip fetching errors by allowing the sync of other swaps to function normally. If we needed the tip but couldn't fetch it, only chain swaps are not synced. Warnings are logged accordingly.
> Optimize bitcoin tip fetch + gracefully handle errors

- cli/Cargo.lock
- lib/Cargo.lock
- lib/core/Cargo.toml
- lib/core/src/persist/backup.rs
- lib/core/src/persist/mod.rs
- lib/wasm/src/lib.rs
This PR fixes a memory leak that affected Wasm packages. The memory allocated by the in-memory database was never cleared, so in a server use case, where many different wallets are loaded/unloaded in a single run, wallets not in use would continue to occupy space.
The `rusqlite` fork was updated so we could access the `MemVfsUtil` struct, which allows deleting a db.
In local tests, I've verified that after these changes, starting and stopping different SDK instances no longer leads to a forever-increasing memory footprint and now plateaus.
> wasm: Clear in-memory db on disconnect

- README.md
- cli/Cargo.lock
- cli/src/commands.rs
- lib/Cargo.lock
- lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
- lib/bindings/src/breez_sdk_liquid.udl
- lib/core/Cargo.toml
- lib/core/src/frb_generated.rs
- lib/core/src/lib.rs
- lib/core/src/model.rs
- lib/core/src/payjoin/side_swap.rs
- lib/core/src/sdk.rs
- lib/core/src/side_swap/api/mod.rs
- lib/core/src/side_swap/api/model.rs
- lib/core/src/side_swap/api/request_handler.rs
- lib/core/src/side_swap/api/response_handler.rs
- lib/core/src/side_swap/mod.rs
- lib/core/src/test_utils/wallet.rs
- lib/core/src/wallet/mod.rs
- lib/wasm/src/model.rs
- packages/dart/lib/src/frb_generated.dart
- packages/dart/lib/src/frb_generated.io.dart
- packages/dart/lib/src/model.dart
- packages/dart/lib/src/model.freezed.dart
- packages/dart/pubspec.yaml
- packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
- packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
- packages/react-native/ios/BreezSDKLiquidMapper.swift
- packages/react-native/src/index.ts
This PR:
- Adds a base WebSocket layer to allow connections and exchange messages with the SideSwap API
- Adds `sideswap_api` as a dependency for the API types (currently pointing to local crate)
> Side-Swap: Add base communication layer and endpoints

- lib/core/src/sdk.rs
Moneybadger has added Bootleggers Coffee to our merchant network, and we are sponsoring Bitcoin meetups there across South Africa. https://www.moneybadger.co.za/meetups
Naturally, the big thing we get asked for is when Blink-based wallets will work :) We also got enquiries from some of the local blink-based wallets (e.g. Blitz)
> add support to scan bootleggers coffee and other yoyo merchants

- .github/workflows/precompile-binaries.yml
This PR introduces minimal changes to be able to test the switch to using [precompiled binaries](https://github.com/irondash/cargokit/blob/main/docs/precompiled_binaries.md) via [Cargokit](https://fzyzcjy.github.io/flutter_rust_bridge/manual/integrate/builtin).
_Ref branch: [cargokit](https://github.com/breez/breez-sdk-liquid/tree/cargokit)_
Our SDK uses `flutter_rust_bridge` to expose a native Rust library to Flutter. When our Flutter plugin is used alongside another Flutter plugin built with `flutter_rust_bridge`, we’ve encountered iOS linking issues:
-  The framework is not found at runtime, or
- The generated framework gets its content hash symbol stripped, breaking initialization.
This PR adopts the recommended approach by frb that's also used by other conflicting plugins: …
> ci: add GitHub Actions workflow for precompiling binaries on release

- lib/core/src/sdk.rs
This at least saves 300 requests per hour if there are chain swaps being monitored.
We need to review the recovery in detail to see the effect of limiting the running of the recovery to new bitcoin blocks. Possibly the only part effected is recovery of the last refund tx 
Partially addresses #977
> Only fetch bitcoin tip on new liquid tip

- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/BreezSdkLiquidConnector.kt
- lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ForegroundService.kt
- lib/bindings/langs/swift/Sources/BreezSDKLiquid/BreezSDKLiquidConnector.swift
Force SDK disconnect during shutdown in case the foreground service isn't stopped
> Notification Plugin: Disconnect SDK during shutdown

- packages/wasm/examples/web-vite/vite.config.ts
This PR aims to fix the Vite's example WebAssembly loading error `CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0` 
The problem was how Vite was handling .wasm and did not include the file - causing the HTML page to load in the `init` function.
> fix: update Vite config to include WASM assets and optimize dependencies
