lib/core/src/swapper.rs

Fix the CI cargo clippy warnings.

Cargo clippy

---

lib/core/src/lib.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/wallet.rs

As an ongoing effort and part of #285 now it is the onchain wallet that gets abstracted away.

Abstract onchain wallet behind its own module and trait

---

cli/src/commands.rs
lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/bindings/src/lib.rs
lib/bindings/tests/bindings/test_breez_liquid_sdk.kts
lib/bindings/tests/bindings/test_breez_liquid_sdk.py
lib/bindings/tests/bindings/test_breez_liquid_sdk.swift
lib/core/src/bindings.rs
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
packages/dart/lib/src/bindings.dart
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/dart/test/breez_liquid_dart_test.dart
packages/flutter/example/lib/routes/home/home_page.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKModule.kt
packages/react-native/example/App.js
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/ios/RNBreezLiquidSDK.m
packages/react-native/ios/RNBreezLiquidSDK.swift
packages/react-native/src/index.ts

This PR removes the argument for `get_info`.

`get_info`: remove `with_scan` argument

---

lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/receive_swap.rs
lib/core/src/sdk.rs
lib/core/src/utils.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/src/index.ts

Receive: Add zero-conf checks and properly manage state updates

---

cli/Cargo.lock
lib/Cargo.lock
lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/core/Cargo.toml
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/persist/cache.rs
lib/core/src/persist/migrations.rs
lib/core/src/persist/mod.rs
lib/core/src/sdk.rs
lib/core/src/swapper/mod.rs
lib/core/src/test_utils.rs
lib/core/src/utils.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/src/index.ts

Use swapper proxy to extract referral ID

---

cli/Cargo.lock
cli/src/commands.rs
lib/Cargo.lock
lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/bindings/src/lib.rs
lib/core/Cargo.toml
lib/core/src/bindings.rs
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/sdk.rs
lib/core/src/utils.rs
packages/dart/lib/src/bindings.dart
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKModule.kt
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/ios/RNBreezLiquidSDK.m
packages/react-native/ios/RNBreezLiquidSDK.swift
packages/react-native/src/index.ts

Add `FiatAPI` methods to Liquid SDK

---

lib/bindings/langs/react-native/src/gen_kotlin/mod.rs
lib/bindings/langs/react-native/src/gen_kotlin/templates/Helpers.kt
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt

This PR fixes conversion of the f32 type in the codegen for react native

Fix handling of f32 type

---

packages/react-native/example/App.js
packages/react-native/example/package.json
packages/react-native/example/yarn.lock

This PR adds example code on how to (prepare) receive and send lightning payments

Add payment examples to the RN app

---

cli/src/commands.rs
lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/bindings/src/lib.rs
lib/core/src/bindings.rs
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
packages/dart/lib/src/bindings.dart
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKModule.kt
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/ios/RNBreezLiquidSDK.swift
packages/react-native/src/index.ts

This PR changes the request/response structs for onchain payments for clarity.

Change onchain request/response structs for clarity

---

.github/workflows/build-bindings-android.yml
.github/workflows/build-bindings-darwin.yml
.github/workflows/build-bindings-ios.yml
.github/workflows/build-bindings-linux.yml
.github/workflows/build-bindings-windows.yml
.github/workflows/build-language-bindings.yml
.github/workflows/main.yml

(cherry picked from commit 317c7906d968eeb6726ab4a9076a8bf64bdf4a6e)

Install protoc on workflow

---

packages/react-native/package.json
packages/react-native/tsconfig.build.json
packages/react-native/yarn.lock

Excludes the "example" directory from type generation to fix the types path

Fix RN type generation

---

lib/bindings/langs/flutter/breez_liquid_sdk/include/breez_liquid_sdk.h
lib/bindings/src/breez_liquid_sdk.udl
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/receive_swap.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/example/lib/utils/config.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezliquidsdk/BreezLiquidSDKMapper.kt
packages/react-native/ios/BreezLiquidSDKMapper.swift
packages/react-native/src/index.ts

Change the Config's zero_conf_min_fee_rate to millisatoshis to prevent floating point inaccuracy.
Fixes #371

Change Config param to zero_conf_min_fee_rate_msat

---

lib/Cargo.lock

Bump lwk_wollet to 0.7.0

---

cli/Cargo.lock
cli/src/commands.rs
lib/Cargo.lock
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/bindings/src/lib.rs
lib/core/Cargo.toml
lib/core/src/bindings.rs
lib/core/src/chain_swap.rs
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/persist/mod.rs
lib/core/src/receive_swap.rs
lib/core/src/sdk.rs
lib/core/src/send_swap.rs
packages/dart/lib/src/bindings.dart
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/example/lib/services/breez_sdk_liquid.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidModule.kt
packages/react-native/example/App.js
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/ios/RNBreezSDKLiquid.m
packages/react-native/ios/RNBreezSDKLiquid.swift
packages/react-native/src/index.ts

This PR add payment filtering by payment type, from/to timestamp and paging. It also sorts payments by reverse chronological order
Fixes #358 #375

List payments filtering and paging

---

packages/react-native/ios/BreezSDKLiquidMapper.swift

Regenerate React Native code with updated `swiftformat`

Regenerate RN

---

lib/bindings/langs/flutter/pubspec.lock
lib/bindings/langs/flutter/scripts/pubspec.lock

Bump `string_scanner` flutter dependency

Fix flutter CI check

---

lib/core/src/persist/chain.rs
lib/core/src/persist/mod.rs
lib/core/src/persist/receive.rs
lib/core/src/persist/send.rs
lib/core/src/sdk.rs
packages/flutter/example/pubspec.lock

This PR extracts `get_where_clause_state_in` and re-uses it to build `WHERE` clauses that filter by state.

Persistence: consolidate state filter

---

lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/wallet.rs

SDK: Add per-wallet directory structure for persister and lwk

---

lib/core/src/event.rs
lib/core/src/persist/cache.rs
lib/core/src/sdk.rs
packages/flutter/example/pubspec.lock

This PR temporarily disables the emitting of events during the first `sync`.
Fixes #300

Pause event notifications on first sync

---

lib/bindings/langs/react-native/src/gen_kotlin/templates/EnumTemplate.kt
lib/bindings/langs/react-native/src/gen_kotlin/templates/macros.kt
lib/bindings/langs/react-native/src/gen_swift/templates/EnumTemplate.swift
lib/bindings/langs/react-native/src/gen_swift/templates/RecordTemplate.swift
lib/bindings/langs/react-native/src/gen_swift/templates/macros.swift
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/example/App.js
packages/react-native/example/ios/Podfile.lock
packages/react-native/example/package.json
packages/react-native/example/yarn.lock
packages/react-native/ios/BreezSDKLiquidMapper.swift

This PR updates the React Native codegen to handle multiple fields in a enum variant

Handle in RN codegen multiple fields in enum variant

---

lib/core/src/sdk.rs

This PR addresses two fixes in `pay-onchain`:
First, our `lockup_fees_sat` were estimated using the `server_lockup_amount`. It's now changed to use the `user_lockup_amount`.
Second, the Boltz fees were calculated based on the `server_lockup_amount`, when it appears it should also be based on the `user_lockup_amount`.

pay-onchain: fix user lockup fee calculation, boltz fee calculation

---

cli/Cargo.lock
cli/src/commands.rs
lib/Cargo.lock
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/bindings/src/lib.rs
lib/core/Cargo.toml
lib/core/src/bindings.rs
lib/core/src/frb_generated.io.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/test_utils/wallet.rs
lib/core/src/wallet.rs
packages/dart/lib/src/bindings.dart
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidModule.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/ios/RNBreezSDKLiquid.m
packages/react-native/ios/RNBreezSDKLiquid.swift
packages/react-native/src/index.ts

This PR adds message signing and checking methods to help sign requests to be sent to the LNURL service
Fixes #277

Add `sign_message` and `check_message`

---

lib/bindings/langs/android/lib/build.gradle.kts
lib/bindings/langs/android/lib/proguard-rules.pro
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/BreezSdkLiquidConnector.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/Constants.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ForegroundService.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/Message.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/MessagingService.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/NotificationHelper.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ResourceHelper.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/ServiceLogger.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/Job.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPay.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPayInfo.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/LnurlPayInvoice.kt
lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/SwapUpdated.kt
lib/bindings/langs/flutter/pubspec.lock

This PR adds the Android notification plugin to handle lnurlpay_info, lnurlpay_invoice and swap_updated push notifications.
Builds on PR #410

Android notification plugin

---

lib/core/src/sdk.rs
packages/flutter/example/pubspec.lock

Ensure non-MRH invoices use lockup amount for fee calculation

---

cli/README.md

This PR as requested in telegram, adds the current CLI commands to the README

Add CLI commands to readme

---

packages/flutter/example/pubspec.lock

chore: `melos pub-upgrade`

---

lib/core/src/model.rs
lib/core/src/sdk.rs

sync: correctly detect payment by refund tx ID

---

lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/core/Cargo.toml
lib/core/src/chain_swap.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/persist/migrations.rs
lib/core/src/persist/mod.rs
lib/core/src/receive_swap.rs
lib/core/src/sdk.rs
lib/core/src/send_swap.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/example/lib/routes/home/widgets/payment_list/widgets/payment_item.dart
packages/flutter/example/lib/routes/home/widgets/receive_payment/receive_payment_dialog.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/src/index.ts

Set `PaymentDetails` as mandatory, default to LiquidAddress

---

lib/core/src/persist/mod.rs

This PR removes the use of a transaction during `insert_or_update_payment()`

Remove transaction

---

cli/src/main.rs
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/langs/flutter/pubspec.lock
lib/bindings/src/breez_sdk_liquid.udl
lib/core/src/chain/liquid.rs
lib/core/src/chain_swap.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/receive_swap.rs
lib/core/src/sdk.rs
lib/core/src/swapper/mod.rs
lib/core/src/test_utils/chain.rs
lib/core/src/test_utils/swapper.rs
lib/core/src/utils.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/src/index.ts

Add lowball broadcast support with API key for all transaction types

---

cli/src/commands.rs
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/core/src/chain_swap.rs
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/example/pubspec.lock
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/src/index.ts

This PR fixes the pay_onchain custom claim fee calculation by reverting the fee rate to sat/vbyte. Also reverts fee rates for Bitcoin transactions to sat/vbyte

Fix pay onchain claim fee

---

lib/bindings/src/lib.rs
lib/core/src/bindings.rs
lib/core/src/chain/bitcoin.rs
lib/core/src/chain_swap.rs
lib/core/src/error.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/swapper/boltz/bitcoin.rs
lib/core/src/swapper/boltz/liquid.rs
lib/core/src/swapper/boltz/mod.rs
lib/core/src/test_utils/chain.rs
packages/dart/lib/src/model.dart

The refundable amount is based on the locked up utxo(s), not the initial swap amount.
To retrieve this, we have to make a chain service lookup.

`list-refundables`: show refundable amount, not swap amount

---

cli/src/commands.rs
lib/core/src/model.rs
lib/core/src/persist/mod.rs
packages/react-native/example/App.js

This PR fixes the SQL clause to filter payments and adds a CLI option to filter payments by type.

Fix list payments filter

---

lib/bindings/langs/flutter/breez_sdk_liquidFFI/include/breez_sdk_liquidFFI.h
lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/ios-arm64/breez_sdk_liquidFFI.framework/Info.plist
lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/ios-arm64_x86_64-simulator/breez_sdk_liquidFFI.framework/Info.plist
lib/bindings/langs/swift/breez_sdk_liquidFFI.xcframework/macos-arm64_x86_64/breez_sdk_liquidFFI.framework/Info.plist
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart

This PR adds an Info.plist file per framework in the xcframework
Fixes breez/breez-sdk-liquid-swift#4

Add swift framework plists

---

cli/src/commands.rs
lib/core/src/chain_swap.rs
lib/core/src/persist/chain.rs

Store claim_address for incoming chain swap when claiming

---

lib/core/src/sdk.rs

This PR validates the Bitcoin address and network before starting the outgoing chain swap.
Fixes #560

Validate the pay_onchain address

---

lib/bindings/langs/android/lib/src/main/kotlin/breez_sdk_liquid_notification/job/SwapUpdated.kt
lib/bindings/langs/swift/Sources/BreezSDKLiquid/Task/SwapUpdated.swift

This PR triggers the payment success notification once the swap claim tx is broadcast and it's waiting confirmation.

Notification Plugin: Notify success when waiting for confirmation

---

.github/workflows/build-bindings-android.yml
.github/workflows/build-bindings-windows.yml
.github/workflows/publish-csharp.yml
.github/workflows/publish-golang.yml
.github/workflows/publish-python.yml
lib/bindings/makefile

This PR removes the 32 bit bindings.

Remove 32bit support

---

lib/core/src/chain/liquid.rs

Fixes #583 
Before, we only expected error codes 429 (Too many requests) and 503 (Service Temporarily Unavailable) and treated all other response types as success. Unless it actually was a success, deserialization of the result body into the expected struct would fail.
With this PR, only success result codes are treated as success. This allows us to retry (with backoff) for response error types.

Fix handling of Esplora API call results

---

cli/src/commands.rs
lib/bindings/src/lib.rs
lib/core/src/bindings.rs
lib/core/src/recover/recoverer.rs
lib/core/src/sdk.rs

Sync improvements

---

lib/core/src/persist/cache.rs
lib/core/src/recover/model.rs

Trigger sync when derivation index changes

Sync derivation index

---

lib/core/src/persist/mod.rs
lib/core/src/sdk.rs

Here we ensure that we override (upsert) unconfirmed transactions with confirmed ones if exist.
fixes https://github.com/breez/misty-breez/issues/266

Update unconfirmed transactions

---

cli/src/main.rs
lib/core/src/sync/client.rs

Reflects changes from breez/data-sync#14

Increase keep-alive time and add CLI sync service variable

---

lib/core/src/sdk.rs

This changes the way we calculate the confirmed balance to summarize all confirmed unspent utxos.
Previously the calculation iterated over all confirmed transactions and summarize their outputs which didn't take into consideration spent utxos that are still in the mempool.
As a result the balance for send swaps, for example, only changed upon confirmation of the sent transaction while the payment succeeded way before (when the swapper revealed the preimage). 
The fix ensures that spent outputs (confirmed and unconfirmed) are not considered as part of the user balance.

fix confirmed balance

---

lib/core/src/model.rs

The boltz fee is being included in both the payment amount and fees for sent payments.
- For sent payments via swap, the amount should match the received amount

Fix the send amount for swap payments

---

cli/src/main.rs

Currently the data-sync is not started if SYNC_SERVICE_URL env is not set. This PR instead makes the data-sync opt-out.

CLI: Make data-sync opt-out

---

lib/core/src/chain_swap.rs

This fixes an issue where a `Refundable` chain swap would be set to `Failed` if the onchain script history fetching failed.
Now, we can distinguish between a failed fetch and a successful one where the the user lockup tx was not found.

Distinguish between failed fetch and tx not found

---

cli/src/main.rs
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/signer.rs
lib/core/src/wallet.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/src/index.ts

This PR adds an optional passphrase to the ConnectRequest to salt the seed
Fixes #721

Add seed passphrase to ConnectRequest

---

cli/Cargo.lock
cli/Cargo.toml
lib/Cargo.lock
lib/bindings/Cargo.toml
lib/core/Cargo.toml

This PR cleans unused dependencies and upgrades all the ones that could be easily upgraded.

Clean and update dependencies

---

cli/src/main.rs
lib/bindings/langs/flutter/breez_sdk_liquid/include/breez_sdk_liquid.h
lib/bindings/src/breez_sdk_liquid.udl
lib/bindings/tests/bindings/golang/test_breez_sdk_liquid.go
lib/core/src/frb_generated.rs
lib/core/src/model.rs
lib/core/src/sdk.rs
lib/core/src/signer.rs
packages/dart/lib/src/frb_generated.dart
packages/dart/lib/src/frb_generated.io.dart
packages/dart/lib/src/model.dart
packages/flutter/lib/flutter_breez_liquid_bindings_generated.dart
packages/react-native/android/src/main/java/com/breezsdkliquid/BreezSDKLiquidMapper.kt
packages/react-native/ios/BreezSDKLiquidMapper.swift
packages/react-native/src/index.ts

Adds an optional seed to the ConnectRequest to support MPC wallets
Fixes #744

Add seed to ConnectRequest

---

lib/core/src/recover/recoverer.rs

Resolves #725.
This PR adds to the tx recovery methods the assumption that the wallet tx map might be out of date (in practice, this means that wallet txs might be included in the swap script histories, but not in the wallet tx map iself).
I've reviewed the current tx recovery implementations, and they mostly conform to this assumption. The main issue I found was that incoming chain swaps didn't consider the possibility of a swapper refund (which was an issue regardless of the new assumptions).

Tolerate older wallet tx map during tx recovery

---

lib/core/src/bindings.rs
lib/core/src/model.rs
lib/core/src/persist/chain.rs
lib/core/src/persist/receive.rs
lib/core/src/persist/send.rs
lib/core/src/sdk.rs

Fixes https://github.com/breez/breez-sdk-liquid/actions/runs/13528420688/job/37804641176?pr=757

Fix Clippy issues

---

lib/core/src/persist/mod.rs

For an overpaid non-amountless chain swap we are displaying the following when sending 59999sat instead of 25000sat:
```
BreezSDKLiquid.Payment(
timestamp: 1741719704, 
amountSat: 24173, 
feesSat: 35826, 
...
```
In this case it's taking the actual payer amount (59999) and receiver amount (24173) and calculating the fee as 59999 - 24173 = 35826. We should only take the actual payer amount if it's an amountless swap, as any other paid amount results in a refund.
- When receiving a fixed BTC amount and overpaying it, the amount and fee in the payment item should remain the same when refundable

Fix payment amount/fee for overpaid non-amountless chain swap

---

.github/workflows/build-language-bindings.yml
.github/workflows/main.yml
.github/workflows/publish-all-platforms.yml
.github/workflows/publish-android.yml
lib/bindings/langs/android/lib/build.gradle.kts
lib/bindings/langs/kotlin-multiplatform/breez-sdk-liquid-kmp/build.gradle.kts
lib/bindings/makefile
packages/flutter/android/build.gradle
packages/flutter/android/build.gradle.production
packages/react-native/android/build.gradle
packages/react-native/example/android/build.gradle

CI test: https://github.com/breez/breez-sdk-liquid/actions/runs/13933531248
Build test: https://github.com/breez/breez-sdk-liquid/actions/runs/13933525533

Downgrade Android to Uniffi 0.25

---

.github/workflows/main.yml
CONTRIBUTING.md
lib/Cargo.lock
lib/wasm/DEVELOPING.md

WASM: Setup emscripten

---

regtest/README.md

This adds some guidance to the regtest readme on using the regtest setup to try out the SDK.

regtest: improve README.md

---

.github/workflows/publish-python.yml
lib/bindings/langs/python/README.md

Add python 3.13 wheels

---

lib/core/src/recover/handlers/handle_send_swap.rs

Println is bleeding into CLI interface 😵‍💫

Fix println

---

lib/wasm/src/lib.rs

Renames prepareReceivePayment exposed method

WASM: Fix minor typo

---

lib/core/src/wallet.rs

This PR fixes an issue where calling `full_scan_to_index` when using waterfalls causes an error:
```
Failed to scan wallet: Generic { err: "UsingWaterfallsWithNonZeroIndex" }
```

Only full_scan_to_index when not using waterfalls

---

.github/workflows/build-bindings-wasm.yml
.github/workflows/publish-all-platforms.yml
.github/workflows/publish-wasm.yml

This PR adds the CI flow for publishing a Wasm package to npm

Wasm publish

---

regtest/.env
regtest/docker-compose.yml

Let's build the data-sync image instead of relying on a published version

regtest: build data-sync image

---

lib/core/src/receive_swap.rs

This PR accelerates receive-swap claims by fast-forwarding the server lockup mempool verification. This is done by broadcasting it ourselves. 
The same could be done on chain swaps, but IMO it isn't worth it given the larger timeframe those entail.

Broadcast receive swap server lockup txs

---

lib/core/src/recover/handlers/handle_receive_swap.rs

This PR addresses (#821) where the recovery of older receive swaps fails if the mrh_address is either missing or invalid.
Previously, any issue parsing the MRH address would result in a recovery error and early exit. This PR improves the robustness of the recovery logic by allowing it to continue based on claim script history alone when the MRH address is:
Empty, or Invalid (e.g., malformed Liquid address)
before 
```makefile
[2025-04-30 04:57:53.052 DEBUG breez_sdk_liquid::recover::handlers::handle_receive_swap:46] [Recover Receive] Recovering data for swap 9tDTqdN3uEcw
[2025-04-30 04:57:53.052 WARN breez_sdk_liquid::recover::recoverer:146] Error recovering data for swap 9tDTqdN3uEcw: Invalid MRH address for swap 9tDTqdN3uEcw
[2025-04-30 04:57:53.058 DEBUG breez_sdk_liquid::sdk:3358] …
```

fix : invalid MRH addresses during Receive Swap recovery

---

lib/core/src/persist/mod.rs

This PR updates the `get_payment` query to always return a payment, even when in the Created or Failed states. This then allows LNURL-verify to correctly query the payment and not return an error before the payment is initiated.
**Builds:**
- Android: https://github.com/breez/misty-breez/actions/runs/15071873025
- iOS 6429.1: https://github.com/breez/misty-breez/actions/runs/15071870599 
Fixes #919

Allow get_payment to get payment no matter the state

---

regtest/waterfalls-service/Dockerfile

Update waterfalls to improve error handling and log error context

Update regtest waterfalls

---

lib/core/src/persist/mod.rs

Use address as destination on incoming liquid payments

---

lib/core/src/sdk.rs

This fixes 2 issues:
- If the chain service provided utxos in a different order from the requested scripts, which we seen happen, this fixes the matching between swaps and their amount
- Also resolves #966 as swaps for which we don't find utxos no longer get included in the refundables

Fix `list_refundables` swap to utxos matching

---

cli/Cargo.lock
lib/Cargo.lock
lib/core/Cargo.toml
lib/core/src/chain/bitcoin/esplora.rs
lib/core/src/recover/recoverer.rs
lib/core/src/sdk.rs
lib/core/src/wallet/mod.rs

This PR:
- Adds a connect timeout to the Bitcoin esplora client
- Adds logging around sync

Add esplora client connect timeout
